#!/usr/bin/env python3
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from builder import L, gp, W, lesson_json, write_lesson
from lessons_04 import lesson_04
from lessons_05 import lesson_05
from lessons_06 import lesson_06
from lessons_07 import lesson_07
from lessons_08 import lesson_08
from lessons_09 import lesson_09
from lessons_10 import lesson_10
from lessons_11_12 import lesson_11, lesson_12


def lesson_02():
    return lesson_json(
        "02", 2, "看房子", "Look at the apartment",
        [
            W("给", "gěi", "prep.", "to, for"),
            W("找", "zhǎo", "v.", "to look for"),
            W("房子", "fángzi", "n.", "house, apartment"),
            W("真", "zhēn", "adv.", "really, indeed"),
            W("离", "lí", "v.", "to be away from"),
            W("公司", "gōngsī", "n.", "company, firm"),
            W("近", "jìn", "adj.", "near, close"),
            W("也", "yě", "adv.", "also, too"),
            W("千", "qiān", "num.", "thousand"),
            W("房间", "fángjiān", "n.", "room"),
            W("每", "měi", "pron.", "every, each"),
            W("公共汽车", "gōnggòngqìchē", "n.", "bus"),
            W("站", "zhàn", "n.", "stop, station"),
            W("两", "liǎng", "num.", "two"),
            W("百", "bǎi", "num.", "hundred"),
            W("米", "mǐ", "m.w.", "meter"),
            W("超市", "chāoshì", "n.", "supermarket"),
            W("远", "yuǎn", "adj.", "far, distant"),
            W("旁边", "pángbiān", "n.", "beside"),
            W("走", "zǒu", "v.", "to walk"),
        ],
        L("Use the lesson word in a new sentence.", [
            "This book is for you.|这 本 书 是 给 你 的|给|。",
            "I am looking for a friend.|我 找 朋友|找|。",
            "The apartment is very close.|房子 很 近|房子|。",
            "This room is really big.|这个 房间 真 大|真|。",
            "School is far from home.|学校 离 家 很 远|离|。",
            "Dad is at the company.|爸爸 在 公司|公司|。",
            "The supermarket is close.|超市 很 近|近|。",
            "I also like this room.|我 也 喜欢 这个 房间|也|。",
            "This book is one thousand kuai.|这 本 书 一 千 块|千|。",
            "Each room is big.|每 个 房间 都 大|每|。",
            "I take the bus.|我 坐 公共汽车|公共汽车|。",
            "The stop is close.|站 很 近|站|。",
            "I am buying two books.|我 买 两 本 书|两|。",
            "Walk two hundred meters.|走 两 百 米|百|。",
            "It is three hundred meters.|三 百 米|米|。",
            "The shop is beside the station.|商店 在 站 旁边|旁边|。",
            "Home is far.|家 很 远|远|。",
            "I walk to school.|我 走 去 学校|走|。",
            "The supermarket is next to home.|超市 在 家 旁边|超市|。",
            "Take a look at this apartment.|你 看看 房子|看看|。",
        ]),
        [
            gp("redup", "Verb reduplication", "AA / A一A",
               "Reduplicating a verb (看看, 问问) makes the action short and light. It is close in meaning to V+一下.",
               "你看看这本书。", "Nǐ kànkan zhè běn shū.", "Take a look at this book.", "g1",
               "Reduplicate the verb for a brief, casual action.", [
                "Take a look at this book.|你 看看 这 本 书|看看|。",
                "Ask the teacher.|你 问问 老师|问问|。",
                "Talk about it.|你 说说|说说|。",
                "Think about it.|我 想想|想想|。",
                "Walk around a bit.|我们 走走|走走|。",
                "Have a look at the apartment.|她 看看 房子|看看|。",
                "Ask your friend.|他 问问 朋友|问问|。",
                "Talk about the company.|你 说说 公司|说说|。",
                "Please look at this room.|请 看看 这个 房间|看看|。",
                "Mom wants to take a look.|妈妈 看看|看看|。",
                "The child is having a look.|孩子 看看|看看|。",
                "Let’s walk a little.|我们 走走|走走|。",
                "Ask dad.|你 问问 爸爸|问问|。",
                "Talk about this friend.|你 说说 朋友|说说|。",
                "Think again.|你 想想|想想|。",
                "Look at the supermarket.|我 看看 超市|看看|。",
                "Ask mom.|我 问问 妈妈|问问|。",
                "Have a look at the rooms.|你 看看 房间|看看|。",
                "Talk about this book.|他 说说 这 本 书|说说|。",
                "Walk with me.|我们 走走|走走|。",
            ]),
            gp("zhen-adj", "真 + adjective", "subject + 真 + adjective",
               "真 is a modal adverb meaning “really.” Put it before an adjective to exclaim about a quality.",
               "这个房间真大。", "Zhège fángjiān zhēn dà.", "This room is really big.", "g2",
               "真 comes right before the adjective.", [
                "This room is really big.|这个 房间 真 大|真|。",
                "That apartment is really close.|那个 房子 真 近|真|。",
                "This dish is really good.|这个 菜 真 好|真|。",
                "The weather is really hot.|天气 真 热|真|。",
                "Her child is really pretty.|她 的 孩子 真 漂亮|真|。",
                "This book is really good.|这 本 书 真 好|真|。",
                "The company is really far.|公司 真 远|真|。",
                "That supermarket is really close.|那个 超市 真 近|真|。",
                "This room is really pretty.|这个 房间 真 漂亮|真|。",
                "Dad is really busy.|爸爸 真 忙|真|。",
                "The cat is really small.|猫 真 小|真|。",
                "This tea is really hot.|这 杯 茶 真 热|真|。",
                "The school is really big.|学校 真 大|真|。",
                "That friend is really nice.|那个 朋友 真 好|真|。",
                "The apartment is really far.|房子 真 远|真|。",
                "This station is really close.|这个 站 真 近|真|。",
                "The child is really happy.|孩子 真 高兴|真|。",
                "Mom is really pretty.|妈妈 真 漂亮|真|。",
                "Today is really hot.|今天 真 热|真|。",
                "This room is really small.|这个 房间 真 小|真|。",
            ]),
            gp("li-distance", "A 离 B", "A 离 B + distance / 近 / 远",
               "离 means “to be away from.” Name two places, then say how far, or 很近 / 很远 / 不远.",
               "学校离家很近。", "Xuéxiào lí jiā hěn jìn.", "School is close to home.", "g3",
               "Put 离 between the two places.", [
                "School is close to home.|学校 离 家 很 近|离|。",
                "The supermarket is not far from here.|超市 离 这儿 不 远|离|。",
                "The company is far from home.|公司 离 家 很 远|离|。",
                "The station is two hundred meters from here.|站 离 这儿 两 百 米|离|。",
                "The airport is far from school.|机场 离 学校 很 远|离|。",
                "His home is close to the company.|他 家 离 公司 很 近|离|。",
                "The shop is close to the station.|商店 离 站 很 近|离|。",
                "The hospital is not far from home.|医院 离 家 不 远|离|。",
                "The stop is close to the supermarket.|站 离 超市 很 近|离|。",
                "My home is far from Beijing.|我 家 离 北京 很 远|离|。",
                "The school is three hundred meters from here.|学校 离 这儿 三 百 米|离|。",
                "The apartment is close to school.|房子 离 学校 很 近|离|。",
                "The company is not far from the airport.|公司 离 机场 不 远|离|。",
                "The supermarket is far from the company.|超市 离 公司 很 远|离|。",
                "Home is close to the shop.|家 离 商店 很 近|离|。",
                "The station is not far from school.|站 离 学校 不 远|离|。",
                "The hospital is far from the airport.|医院 离 机场 很 远|离|。",
                "The room is close to the shop.|房间 离 商店 很 近|离|。",
                "Beijing is far from here.|北京 离 这儿 很 远|离|。",
                "The company is two hundred meters from home.|公司 离 家 两 百 米|离|。",
            ]),
            gp("mei-dou", "每…都", "每 + measure word + noun + 都 + predicate",
               "每 means each/every. It usually needs a measure word, and 都 follows the noun. 每天 and 每年 need no extra measure word.",
               "每个房间都很大。", "Měi ge fángjiān dōu hěn dà.", "Every room is very big.", "g4",
               "每…都: measure word, then 都 after the noun.", [
                "Every room is very big.|每 个 房间 都 很 大|每|。",
                "Every student likes Chinese.|每 个 学生 都 喜欢 汉语|每|。",
                "Every book is new.|每 本 书 都 新|每|。",
                "Every day I walk.|每 天 都 走|每|。",
                "Every friend is here.|每 个 朋友 都 在|每|。",
                "Every company is far.|每 个 公司 都 很 远|每|。",
                "Every child is happy.|每 个 孩子 都 很 高兴|每|。",
                "Every apartment is close.|每 个 房子 都 很 近|每|。",
                "Every year he comes.|每 年 都 来|每|。",
                "Every room is pretty.|每 个 房间 都 很 漂亮|每|。",
                "Every teacher works.|每 个 老师 都 工作|每|。",
                "Every supermarket is big.|每 个 超市 都 很 大|每|。",
                "Every day she reads.|每 天 都 看 书|每|。",
                "Every student is here.|每 个 学生 都 在|每|。",
                "Every station is close.|每 个 站 都 很 近|每|。",
                "Every day dad goes to the company.|爸爸 每 天 都 去 公司|每|。",
                "Every child likes cats.|每 个 孩子 都 喜欢 猫|每|。",
                "Every book is good.|每 本 书 都 很 好|每|。",
                "Every friend walks.|每 个 朋友 都 走|每|。",
                "Every room has a table.|每 个 房间 都 有 桌子|每|。",
            ]),
        ],
    )


def lesson_03():
    return lesson_json(
        "03", 3, "去公司", "Go to the company",
        [
            W("要", "yào", "mod.", "to want to, would like to"),
            W("牛奶", "niúnǎi", "n.", "milk"),
            W("咖啡", "kāfēi", "n.", "coffee"),
            W("第一", "dì yī", "num.", "first"),
            W("新", "xīn", "adj.", "new"),
            W("上班", "shàngbān", "v.", "to go to work"),
            W("再", "zài", "adv.", "again, once more"),
            W("别", "bié", "adv.", "don’t, stop"),
            W("对", "duì", "prep.", "to, for"),
            W("身体", "shēntǐ", "n.", "body, health"),
            W("报纸", "bàozhǐ", "n.", "newspaper"),
            W("迟到", "chídào", "v.", "to be late"),
            W("等", "děng", "v.", "to wait"),
            W("送", "sòng", "v.", "to give a ride / deliver"),
            W("可以", "kěyǐ", "mod.", "can, may"),
            W("快", "kuài", "adj.", "quick, fast"),
            W("进", "jìn", "v.", "to enter"),
            W("大家", "dàjiā", "pron.", "everybody"),
            W("姓", "xìng", "v./n.", "surname"),
        ],
        L("Use the lesson word in a new sentence.", [
            "I want to drink milk.|我 要 喝 牛奶|要|。",
            "She does not want coffee.|她 不 想 喝 咖啡|咖啡|。",
            "Today is the first day.|今天 是 第一 天|第一|。",
            "This is a new company.|这 是 新 公司|新|。",
            "Dad goes to work in the morning.|爸爸 早上 上班|上班|。",
            "I want to drink another cup.|我 想 再 喝 一 杯|再|。",
            "Don’t be late.|别 迟到|别|。",
            "Coffee is bad for your health.|咖啡 对 身体 不 好|对|。",
            "I am waiting.|我 在 等|等|。",
            "He can come in.|他 可以 进|可以|。",
            "Everyone is here.|大家 都 在|大家|。",
            "My surname is Wang.|我 姓 王|姓|。",
            "Don’t read the newspaper.|别 看 报纸|报纸|。",
            "She will give me a ride.|她 送 我 去 公司|送|。",
            "Come in quickly.|快 进|快|。",
            "Milk is good.|牛奶 很 好|牛奶|。",
            "I am waiting for a friend.|我 等 朋友|等|。",
            "He is late today.|他 今天 迟到|迟到|。",
            "You may drink tea.|你 可以 喝 茶|可以|。",
            "Everyone likes coffee.|大家 喜欢 咖啡|大家|。",
        ]),
        [
            gp("yao-v", "要 + verb", "subject + 要 + verb",
               "要 as a modal verb means “want to.” Put it before another verb. The usual negative is 不想, not 不要.",
               "我要喝牛奶。", "Wǒ yào hē niúnǎi.", "I want to drink milk.", "g1",
               "要 + verb. Negate with 不想.", [
                "I want to drink milk.|我 要 喝 牛奶|要|。",
                "He wants to learn Chinese.|他 要 学习 汉语|要|。",
                "She wants to eat rice.|她 要 吃 米饭|要|。",
                "I want to go to work.|我 要 上班|要|。",
                "They want to drink coffee.|他们 要 喝 咖啡|要|。",
                "I don’t want to drink milk.|我 不想 喝 牛奶|不想|。",
                "He doesn’t want to eat.|他 不想 吃|不想|。",
                "I want to wait.|我 要 等|要|。",
                "She wants to come in.|她 要 进|要|。",
                "Dad wants to read the newspaper.|爸爸 要 看 报纸|要|。",
                "The child wants to drink tea.|孩子 要 喝 茶|要|。",
                "I want to look for a company.|我 要 找 公司|要|。",
                "We want to go home.|我们 要 回 家|要|。",
                "Mom wants to buy coffee.|妈妈 要 买 咖啡|要|。",
                "I don’t want to be late.|我 不想 迟到|不想|。",
                "He wants to give you a ride.|他 要 送 你|要|。",
                "She doesn’t want coffee.|她 不想 喝 咖啡|不想|。",
                "I want to see everyone.|我 要 看 大家|要|。",
                "They want a new apartment.|他们 要 找 新 房子|要|。",
                "Do you want to drink milk?|你 要 喝 牛奶 吗|要|？",
            ]),
            gp("di-number", "第 + number", "第 + number (+ measure) + noun",
               "第 turns a number into an ordinal: 第一 first, 第二天 the next day, 第三个 the third one.",
               "今天是第一天。", "Jīntiān shì dì-yī tiān.", "Today is the first day.", "g2",
               "第 + number makes an ordinal.", [
                "Today is the first day.|今天 是 第一 天|第一|。",
                "This is the second book.|这 是 第二 本 书|第二|。",
                "He is the first student.|他 是 第一 个 学生|第一|。",
                "Tomorrow is the third day.|明天 是 第三 天|第三|。",
                "This is the first cup of coffee.|这 是 第一 杯 咖啡|第一|。",
                "That is the second company.|那 是 第二 个 公司|第二|。",
                "I am reading the first book.|我 看 第一 本 书|第一|。",
                "She bought the third apple.|她 买 第三 个 苹果|第三|。",
                "This is my first day at work.|今天 是 我 第一 天 上班|第一|。",
                "He lives in the second room.|他 住 第二 个 房间|第二|。",
                "The first friend is here.|第一 个 朋友 在|第一|。",
                "This is the fourth day.|今天 是 第四 天|第四|。",
                "I want the first cup.|我 要 第一 杯|第一|。",
                "The second child is small.|第二 个 孩子 很 小|第二|。",
                "This is the first newspaper.|这 是 第一 张 报纸|第一|。",
                "The third room is big.|第三 个 房间 很 大|第三|。",
                "The first day is Monday.|第一 天 是 星期一|第一|。",
                "The second cup is hot.|第二 杯 很 热|第二|。",
                "This is the first company.|这 是 第一 个 公司|第一|。",
                "I like the second book.|我 喜欢 第二 本 书|第二|。",
            ]),
            gp("zai-again", "再 + verb", "modal + 再 + verb",
               "再 means “again / another time.” It sits before the verb. If there is a modal (想, 要, 会, 可以), 再 comes after the modal.",
               "我想再喝一杯咖啡。", "Wǒ xiǎng zài hē yì bēi kāfēi.", "I want to drink another cup of coffee.", "g3",
               "再 goes after a modal and before the verb.", [
                "I want to drink another cup of coffee.|我 想 再 喝 一 杯 咖啡|再|。",
                "He will come again tomorrow.|他 明天 会 再 来|再|。",
                "Let me look again.|我 再 看 一下|再|。",
                "I want to buy one more cup.|我 想 再 买 一 个 杯子|再|。",
                "Please say it again.|你 再 说|再|。",
                "We will wait a bit more.|我们 再 等|再|。",
                "She wants to read the paper again.|她 想 再 看 报纸|再|。",
                "Come in again.|你 再 进|再|。",
                "I will ask again.|我 再 问 一下|再|。",
                "Drink some more milk.|再 喝 牛奶|再|。",
                "He will study again tomorrow.|他 明天 再 学习|再|。",
                "I want to go again.|我 想 再 去|再|。",
                "She can wait a little more.|她 可以 再 等|再|。",
                "Let’s walk a bit more.|我们 再 走|再|。",
                "I will introduce him again.|我 再 介绍 一下|再|。",
                "Buy one more book.|再 买 一 本 书|再|。",
                "He wants to eat more.|他 要 再 吃|再|。",
                "Look at the room again.|再 看 房间|再|。",
                "I will send you again tomorrow.|我 明天 再 送 你|再|。",
                "She will not be late again.|她 不 再 迟到|再|。",
            ]),
            gp("dui", "对…好 / 不好", "A 对 B + adjective",
               "对 is a preposition meaning “to / for.” The pattern is A 对 B + adj./verb, often 好 or 不好.",
               "喝咖啡对身体不好。", "Hē kāfēi duì shēntǐ bù hǎo.", "Drinking coffee is bad for your health.", "g4",
               "对 sits before the person or thing that is affected.", [
                "Drinking coffee is bad for your health.|喝 咖啡 对 身体 不 好|对|。",
                "Drinking milk is good for the body.|喝 牛奶 对 身体 好|对|。",
                "The teacher is nice to the students.|老师 对 学生 很 好|对|。",
                "Watching TV is bad for the body.|看 电视 对 身体 不 好|对|。",
                "Walking is good for your health.|走 对 身体 好|对|。",
                "This book is good for learning Chinese.|这 本 书 对 学习 汉语 好|对|。",
                "Mom is nice to the child.|妈妈 对 孩子 很 好|对|。",
                "Coffee is not good for dad.|咖啡 对 爸爸 不 好|对|。",
                "Work is tiring for her.|工作 对 她 很 忙|对|。",
                "Friends are good to me.|朋友 对 我 很 好|对|。",
                "This tea is good for the body.|这 杯 茶 对 身体 好|对|。",
                "Being late is bad for work.|迟到 对 工作 不 好|对|。",
                "Reading is good for students.|看 书 对 学生 好|对|。",
                "The company is good to everyone.|公司 对 大家 很 好|对|。",
                "Hot weather is bad for the child.|热 对 孩子 不 好|对|。",
                "Chinese is good for work.|汉语 对 工作 好|对|。",
                "This room is good for studying.|这个 房间 对 学习 好|对|。",
                "Milk is good for the child.|牛奶 对 孩子 好|对|。",
                "She is nice to everyone.|她 对 大家 很 好|对|。",
                "Eating too much is bad for you.|吃 太 多 对 身体 不 好|对|。",
            ]),
            gp("bie-buyao", "别 / 不要…了", "别 / 不要 + verb + 了",
               "别 or 不要 plus a verb (often with 了) tells someone to stop or not to do something.",
               "别看报纸了。", "Bié kàn bàozhǐ le.", "Stop reading the newspaper.", "g5",
               "别 / 不要 + verb. 了 often adds “stop doing that.”", [
                "Stop reading the newspaper.|别 看 报纸 了|别|。",
                "Don’t be late.|别 迟到|别|。",
                "Don’t drink coffee.|不要 喝 咖啡 了|不要|。",
                "Don’t come in.|别 进|别|。",
                "Stop waiting.|别 等 了|别|。",
                "Don’t read this book.|不要 看 这 本 书 了|不要|。",
                "Don’t go to work today.|今天 别 上班|别|。",
                "Stop talking.|别 说 了|别|。",
                "Don’t drink milk.|别 喝 牛奶 了|别|。",
                "Don’t look for him.|别 找 他|别|。",
                "Stop eating.|不要 吃 了|不要|。",
                "Don’t wait for me.|别 等 我|别|。",
                "Don’t be late tomorrow.|明天 别 迟到|别|。",
                "Stop watching TV.|别 看 电视 了|别|。",
                "Don’t go out.|别 出 去|别|。",
                "Don’t send him today.|今天 不要 送 他|不要|。",
                "Stop drinking tea.|别 喝 茶 了|别|。",
                "Don’t go in.|不要 进|不要|。",
                "Don’t ask the teacher.|别 问 老师|别|。",
                "Stop walking.|别 走 了|别|。",
            ]),
        ],
    )


def main() -> None:
    lessons = [
        lesson_02(),
        lesson_03(),
        lesson_04(),
        lesson_05(),
        lesson_06(),
        lesson_07(),
        lesson_08(),
        lesson_09(),
        lesson_10(),
        lesson_11(),
        lesson_12(),
    ]
    for lesson in lessons:
        path = write_lesson(lesson)
        n_g = sum(
            len(p["exercises"]["fill"]) + len(p["exercises"]["scramble"]) + len(p["exercises"]["translate"])
            for p in lesson["grammar"]
        )
        n_v = sum(len(lesson["vocabExercises"][k]) for k in ("fill", "scramble", "translate"))
        print(f"wrote {path.name}  words={len(lesson['words'])} vocab={n_v} grammar_items={n_g} points={len(lesson['grammar'])}")
    from builder import MISSING_PY
    if MISSING_PY:
        raise SystemExit("Missing pinyin:\n" + "\n".join(sorted(MISSING_PY)))


if __name__ == "__main__":
    main()
