from builder import L, gp, W, lesson_json


def lesson_10():
    return lesson_json(
        "10", 10, "过生日", "Celebrating a birthday",
        [
            W("问", "wèn", "v.", "to ask"),
            W("问题", "wèntí", "n.", "question, problem"),
            W("阿姨", "āyí", "n.", "aunt"),
            W("面条", "miàntiáo", "n.", "noodles"),
            W("希望", "xīwàng", "v.", "to hope"),
            W("生命", "shēngmìng", "n.", "life"),
            W("长", "cháng", "adj.", "long"),
            W("娃娃", "wáwa", "n.", "doll"),
            W("它", "tā", "pron.", "it"),
            W("唱歌", "chànggē", "v.", "to sing"),
            W("跳舞", "tiàowǔ", "v.", "to dance"),
            W("照相", "zhàoxiàng", "v.", "to take a picture"),
            W("高", "gāo", "adj.", "tall, high"),
            W("往", "wǎng", "prep.", "towards"),
            W("左边", "zuǒbian", "n.", "left side"),
            W("右边", "yòubian", "n.", "right side"),
            W("笑", "xiào", "v.", "to smile, to laugh"),
            W("意思", "yìsi", "n.", "meaning"),
        ],
        L("Use the lesson word in a new sentence.", [
            "I want to ask.|我 想 问|问|。",
            "I have a question.|我 有 问题|问题|。",
            "Aunt is here.|阿姨 在|阿姨|。",
            "Chinese people eat noodles.|中国 人 吃 面条|面条|。",
            "I hope you are happy.|我 希望 你 高兴|希望|。",
            "Life is long.|生命 很 长|生命|。",
            "Noodles are long.|面条 很 长|长|。",
            "The doll can sing.|娃娃 会 唱歌|娃娃|。",
            "It can dance.|它 会 跳舞|它|。",
            "Let’s take a photo.|我们 照相 吧|照相|。",
            "He is very tall.|他 很 高|高|。",
            "Go to the left.|往 左边 走|往|。",
            "Stand on the right.|在 右边 站|右边|。",
            "Smile a little.|笑 一下|笑|。",
            "What’s the meaning?|什么 意思|意思|？",
            "Aunt gave me a doll.|阿姨 给 我 娃娃|阿姨|。",
            "I like singing.|我 喜欢 唱歌|唱歌|。",
            "She likes dancing.|她 喜欢 跳舞|跳舞|。",
            "The left side is pretty.|左边 很 漂亮|左边|。",
            "This is interesting.|这 很 有 意思|意思|。",
        ]),
        [
            gp("dou-le", "都…了", "都 + situation + 了",
               "都…了 means “already” with emphasis or complaint: it’s already this late / you’ve already waited so long. Often paired with 还.",
               "都七点了，爸爸怎么还没回来？", "Dōu qī diǎn le, bàba zěnme hái méi huílai?", "It’s already seven. Why isn’t dad back yet?", "g1",
               "都…了 emphasizes “already,” often with 还.", [
                "It’s already seven.|都 七 点 了|都|。",
                "I’ve already waited an hour.|我 都 等 一 个 小时 了|都|。",
                "He has already rested two months.|他 都 休息 两 个 月 了|都|。",
                "It’s already ten, and he’s still sleeping.|都 十 点 了 他 还 在 睡觉|都|。",
                "You’re already a student.|你 都 是 学生 了|都|。",
                "I’ve already asked.|我 都 问 了|都|。",
                "The noodles are already cold.|面条 都 冷 了|都|。",
                "Aunt has already come.|阿姨 都 来 了|都|。",
                "It’s already evening.|都 晚上 了|都|。",
                "Dad still isn’t back, and it’s already seven.|都 七 点 了 爸爸 还 没 回来|都|。",
                "I’ve already taken the photo.|我 都 照相 了|都|。",
                "She has already sung.|她 都 唱歌 了|都|。",
                "The child has already danced.|孩子 都 跳舞 了|都|。",
                "You’re already this tall.|你 都 这么 高 了|都|。",
                "I’ve already smiled.|我 都 笑 了|都|。",
                "It’s already my birthday.|都 是 我 的 生日 了|都|。",
                "They have already waited.|他们 都 等 了|都|。",
                "The doll already sings.|娃娃 都 会 唱歌 了|都|。",
                "I’ve already hoped too long.|我 都 希望 很 长 时间 了|都|。",
                "He’s already left, and you’re still here.|他 都 走 了 你 还 在|都|。",
            ]),
            gp("jiu-early", "就…了 (early / quick)", "time + 就 + verb + 了",
               "就…了 after a time word says something happened earlier or faster than expected.",
               "我十分钟就到家了。", "Wǒ shí fēnzhōng jiù dào jiā le.", "I’ll be home in just ten minutes.", "g2",
               "就…了 = earlier or quicker than you think.", [
                "I’ll be home in just ten minutes.|我 十 分钟 就 到 家 了|就|。",
                "He went to bed at seven already.|他 七 点 就 睡觉 了|就|。",
                "She started Chinese at five.|她 五 岁 就 开始 学 汉语 了|就|。",
                "The plane arrives in an hour.|坐 飞机 一 个 小时 就 到 了|就|。",
                "Aunt arrived at six already.|阿姨 六 点 就 到 了|就|。",
                "I finished in two minutes.|我 两 分钟 就 做完 了|就|。",
                "He smiled at once.|他 就 笑 了|就|。",
                "We’ll be there soon.|我们 就 到 了|就|。",
                "The child slept at eight already.|孩子 八 点 就 睡觉 了|就|。",
                "I knew at once.|我 就 知道 了|就|。",
                "She came back in ten minutes.|她 十 分钟 就 回来 了|就|。",
                "Dad arrived early.|爸爸 很 早 就 到 了|就|。",
                "The photo was done quickly.|照相 很 快 就 好 了|就|。",
                "Noodles were ready at once.|面条 就 好 了|就|。",
                "They started dancing at once.|他们 就 跳舞 了|就|。",
                "I’ll ask now.|我 现在 就 问|就|。",
                "He left at six already.|他 六 点 就 走 了|就|。",
                "Younger sister got up at six.|妹妹 六 点 就 起床 了|就|。",
                "The meaning was clear at once.|我 就 懂 意思 了|就|。",
                "Wait a bit and we’ll start.|我们 就 开始 了|就|。",
            ]),
            gp("wang", "往 + direction + verb", "往 + 左边 / 右边 / 前 + verb",
               "往 is a preposition meaning “towards.” Pattern: 往 + place/direction + verb.",
               "你往左边站一点儿。", "Nǐ wǎng zuǒbian zhàn yìdiǎnr.", "Move a little to the left.", "g3",
               "往 + direction + verb.", [
                "Move a little to the left.|你 往 左边 站 一点儿|往|。",
                "Move a little to the right.|你 往 右边 站 一点儿|往|。",
                "They went outside.|他们 往 外面 走 了|往|。",
                "Look ahead.|你 往 前 看|往|。",
                "Walk to the left.|往 左边 走|往|。",
                "Run to the right.|往 右边 跑|往|。",
                "Stand on the left a bit.|往 左边 站|往|。",
                "The child ran over there.|孩子 往 那儿 跑 了|往|。",
                "Please look to the right.|请 往 右边 看|往|。",
                "Go towards the door.|往 门 走|往|。",
                "Come towards me.|往 我 这儿 来|往|。",
                "Walk towards the station.|往 站 走|往|。",
                "Dad went outside.|爸爸 往 外面 去 了|往|。",
                "Smile to the left.|往 左边 笑|往|。",
                "Aunt stood on the right.|阿姨 往 右边 站|往|。",
                "Move towards home.|往 家 走|往|。",
                "Look to the left.|往 左边 看|往|。",
                "They walked to the right.|他们 往 右边 走|往|。",
                "The doll faces the left.|娃娃 往 左边|往|。",
                "Please go outside.|请 往 外面 走|往|。",
            ]),
        ],
    )
