from builder import L, gp, W, lesson_json


def lesson_06():
    return lesson_json(
        "06", 6, "计划旅游", "Planning a trip",
        [
            W("准备", "zhǔnbèi", "v.", "to intend, to plan"),
            W("旅游", "lǚyóu", "v.", "to travel"),
            W("可能", "kěnéng", "aux.", "maybe, perhaps"),
            W("泰国", "Tàiguó", "n.", "Thailand"),
            W("过", "guo", "part.", "past experience"),
            W("便宜", "piányi", "adj.", "cheap"),
            W("日", "rì", "n.", "day, date"),
            W("从", "cóng", "prep.", "from"),
            W("小时", "xiǎoshí", "n.", "hour"),
            W("火车", "huǒchē", "n.", "train"),
            W("票", "piào", "n.", "ticket"),
            W("火车站", "huǒchēzhàn", "n.", "train station"),
            W("手机", "shǒujī", "n.", "cell phone"),
            W("告诉", "gàosu", "v.", "to tell"),
            W("知道", "zhīdào", "v.", "to know"),
            W("以后", "yǐhòu", "n.", "after, later"),
        ],
        L("Use the lesson word in a new sentence.", [
            "I plan to travel.|我 准备 去 旅游|准备|。",
            "They like to travel.|他们 喜欢 旅游|旅游|。",
            "I may go tomorrow.|我 可能 明天 去|可能|。",
            "Thailand is pretty.|泰国 很 漂亮|泰国|。",
            "Have you been there?|你 去 过 吗|过|？",
            "Things are cheap.|东西 很 便宜|便宜|。",
            "The first of the month.|一 日|日|。",
            "From Beijing.|从 北京|从|。",
            "It takes two hours.|要 两 个 小时|小时|。",
            "I take the train.|我 坐 火车|火车|。",
            "I bought a ticket.|我 买 票 了|票|。",
            "I am at the train station.|我 在 火车站|火车站|。",
            "This phone is new.|这个 手机 很 新|手机|。",
            "Please tell me.|请 告诉 我|告诉|。",
            "I know.|我 知道|知道|。",
            "See you later.|以后 见|以后|。",
            "I plan to buy a ticket.|我 准备 买 票|准备|。",
            "The train ticket is cheap.|火车 票 很 便宜|便宜|。",
            "Tell mom.|告诉 妈妈|告诉|。",
            "I know this.|我 知道 这个|知道|。",
        ]),
        [
            gp("deshihou", "…的时候", "time / verb phrase + 的时候",
               "的时候 means “when…” after a time word or a verb phrase.",
               "我五岁的时候喜欢猫。", "Wǒ wǔ suì de shíhou xǐhuan māo.", "When I was five I liked cats.", "g1",
               "的时候 = when (that time).", [
                "When I was five I liked cats.|我 五 岁 的时候 喜欢 猫|的时候|。",
                "When it is eight in the morning.|早上 八 点 的时候|的时候|。",
                "When I sleep.|我 睡觉 的时候|的时候|。",
                "When mom cooks.|妈妈 做 饭 的时候|的时候|。",
                "When dad works.|爸爸 上班 的时候|的时候|。",
                "When I travel.|我 旅游 的时候|的时候|。",
                "When she waits.|她 等 的时候|的时候|。",
                "When we rest.|我们 休息 的时候|的时候|。",
                "When the child gets up.|孩子 起床 的时候|的时候|。",
                "When I take the train.|我 坐 火车 的时候|的时候|。",
                "When it is hot.|天气 热 的时候|的时候|。",
                "When I was a student.|我 是 学生 的时候|的时候|。",
                "When they take an exam.|他们 考试 的时候|的时候|。",
                "When you go to the company.|你 去 公司 的时候|的时候|。",
                "When I use the phone.|我 用 手机 的时候|的时候|。",
                "When younger sister reads.|妹妹 看 书 的时候|的时候|。",
                "When we start class.|我们 开始 课 的时候|的时候|。",
                "When he is at the station.|他 在 火车站 的时候|的时候|。",
                "When I buy tickets.|我 买 票 的时候|的时候|。",
                "When you know.|你 知道 的时候|的时候|。",
            ]),
            gp("keneng", "可能", "subject + 可能 + verb / 可能 + subject + verb",
               "可能 means “maybe / probably.” It can go before or after the subject.",
               "我们可能会去泰国。", "Wǒmen kěnéng huì qù Tàiguó.", "We may go to Thailand.", "g2",
               "可能 marks a guess: maybe.", [
                "We may go to Thailand.|我们 可能 去 泰国|可能|。",
                "I may know her.|我 可能 认识 她|可能|。",
                "He may not go.|他 可能 不 去 了|可能|。",
                "She might not know.|她 可能 不 知道|可能|。",
                "It may rain.|可能 下雨|可能|。",
                "They may take the train.|他们 可能 坐 火车|可能|。",
                "I may buy a ticket tomorrow.|我 明天 可能 买 票|可能|。",
                "Dad may come.|爸爸 可能 来|可能|。",
                "The ticket may be cheap.|票 可能 很 便宜|可能|。",
                "We may wait two hours.|我们 可能 等 两 个 小时|可能|。",
                "She may travel.|她 可能 去 旅游|可能|。",
                "He may be at the station.|他 可能 在 火车站|可能|。",
                "I may tell you later.|我 以后 可能 告诉 你|可能|。",
                "The phone may be new.|手机 可能 很 新|可能|。",
                "They may start at eight.|他们 可能 八 点 开始|可能|。",
                "Younger sister may like Thailand.|妹妹 可能 喜欢 泰国|可能|。",
                "I may not have time.|我 可能 没有 时间|可能|。",
                "He may be late.|他 可能 迟到|可能|。",
                "We may go from Beijing.|我们 可能 从 北京 去|可能|。",
                "You may already know.|你 可能 已经 知道 了|可能|。",
            ]),
            gp("guo-exp", "Verb + 过", "verb + 过 (+ object)",
               "过 after a verb marks a past experience. Negate with 没(有) before the verb. Don’t use 了 with this 过.",
               "你去过泰国吗？", "Nǐ qùguo Tàiguó ma?", "Have you been to Thailand?", "g3",
               "Verb + 过 = have ever done. Negative: 没 + verb + 过.", [
                "Have you been to Thailand?|你 去 过 泰国 吗|过|？",
                "I have been to his home.|我 去 过 他 家|过|。",
                "She has read this book.|她 看 过 这 本 书|过|。",
                "They have come to China.|他们 来 过 中国|过|。",
                "I have taken a plane.|我 坐 过 飞机|过|。",
                "I have not been to Thailand.|我 没 去 过 泰国|过|。",
                "He has not seen this.|他 没 看 过|过|。",
                "Have you eaten this dish?|你 吃 过 这个 菜 吗|过|？",
                "I have used a phone.|我 用 过 手机|过|。",
                "She has taken a train.|她 坐 过 火车|过|。",
                "We have traveled.|我们 旅游 过|过|。",
                "Dad has not been to Beijing.|爸爸 没 去 过 北京|过|。",
                "I have asked the teacher.|我 问 过 老师|过|。",
                "He has drunk coffee.|他 喝 过 咖啡|过|。",
                "Have they worked here?|他们 在 这儿 工作 过 吗|过|？",
                "I have never waited that long.|我 没 等 过|过|。",
                "Younger sister has seen an airplane.|妹妹 看 过 飞机|过|。",
                "I have bought tickets.|我 买 过 票|过|。",
                "She has not told me.|她 没 告诉 过 我|过|。",
                "Have you been to the train station?|你 去 过 火车站 吗|过|？",
            ]),
            gp("cong-dao", "从 A 到 B", "从 A 到 B",
               "从 A 到 B marks a range from place or time A to B. You can add how long it takes.",
               "从北京到泰国要四个多小时。", "Cóng Běijīng dào Tàiguó yào sì ge duō xiǎoshí.", "From Beijing to Thailand takes a little over four hours.", "g4",
               "从 A 到 B = from A to B.", [
                "From Beijing to Thailand.|从 北京 到 泰国|从|。",
                "From home to the company.|从 家 到 公司|从|。",
                "From the school to the station.|从 学校 到 站|从|。",
                "From here to the airport.|从 这儿 到 机场|从|。",
                "From Beijing to Shanghai.|从 北京 到 上海|到|。",
                "From the train station to home.|从 火车站 到 家|从|。",
                "From morning to evening.|从 早上 到 晚上|从|。",
                "From one o’clock to three.|从 一 点 到 三 点|到|。",
                "It takes two hours from here to school.|从 这儿 到 学校 要 两 个 小时|从|。",
                "From the supermarket to the company.|从 超市 到 公司|从|。",
                "From China to Thailand.|从 中国 到 泰国|到|。",
                "From my home to the hospital.|从 我 家 到 医院|从|。",
                "From the classroom to the shop.|从 教室 到 商店|从|。",
                "From today to tomorrow.|从 今天 到 明天|从|。",
                "From the airport to the train station.|从 机场 到 火车站|到|。",
                "From work to home.|从 公司 到 家|从|。",
                "From seven to nine.|从 七 点 到 九 点|到|。",
                "From this room to that room.|从 这个 房间 到 那个 房间|从|。",
                "From Beijing to Thailand takes four hours.|从 北京 到 泰国 要 四 个 小时|从|。",
                "From the station to the supermarket.|从 站 到 超市|到|。",
            ]),
        ],
    )
