from builder import L, gp, W, lesson_json


def lesson_05():
    return lesson_json(
        "05", 5, "谁的汉语说的最好", "Who speaks Chinese the best",
        [
            W("班", "bān", "n.", "class"),
            W("男", "nán", "adj.", "male"),
            W("女", "nǚ", "adj.", "female"),
            W("觉得", "juéde", "v.", "to think, to feel"),
            W("得", "de", "part.", "introduces a complement"),
            W("最", "zuì", "adv.", "most"),
            W("哥哥", "gēge", "n.", "elder brother"),
            W("起床", "qǐchuáng", "v.", "to get up"),
            W("考试", "kǎoshì", "n./v.", "exam / to take an exam"),
            W("教室", "jiàoshì", "n.", "classroom"),
            W("零", "líng", "num.", "zero"),
            W("妹妹", "mèimei", "n.", "younger sister"),
            W("为什么", "wèishénme", "pron.", "why"),
            W("道", "dào", "m.w.", "for questions"),
            W("题", "tí", "n.", "question, problem"),
        ],
        L("Use the lesson word in a new sentence.", [
            "Our class is big.|我们 班 很 大|班|。",
            "He is a male student.|他 是 男 学生|男|。",
            "She is a female student.|她 是 女 学生|女|。",
            "I think this is good.|我 觉得 这 很 好|觉得|。",
            "He speaks well.|他 说 得 很 好|得|。",
            "She is the tallest.|她 最 高|最|。",
            "My elder brother is at home.|哥哥 在 家|哥哥|。",
            "I get up at seven.|我 七 点 起床|起床|。",
            "Today we have an exam.|今天 有 考试|考试|。",
            "The classroom is big.|教室 很 大|教室|。",
            "It is five past seven.|七 点 零 五 分|零|。",
            "Younger sister likes books.|妹妹 喜欢 书|妹妹|。",
            "Why are you late?|你 为什么 迟到|为什么|？",
            "I have several questions.|我 有 几 道 题|道|。",
            "This question is hard.|这 道 题 不 好|题|。",
            "The class has twenty students.|班 有 二十 个 学生|班|。",
            "I think the coffee is hot.|我 觉得 咖啡 很 热|觉得|。",
            "Get up quickly.|快 起床|起床|。",
            "The exam is in the classroom.|考试 在 教室|教室|。",
            "Elder brother speaks the best.|哥哥 说 得 最 好|最|。",
        ]),
        [
            gp("duo-adj", "多 + adjective", "多 + 大 / 远 / 长 / 高",
               "多 + adjective asks a content question: 多大 how old/big, 多远 how far, 多长时间 how long.",
               "你学汉语多长时间了？", "Nǐ xué Hànyǔ duō cháng shíjiān le?", "How long have you been studying Chinese?", "g1",
               "多 + adjective asks “how…?”", [
                "How old are you?|你 多 大|多|？",
                "How big is this apartment?|这个 房子 多 大|多|？",
                "How tall is your brother?|哥哥 多 高|多|？",
                "How far is the airport?|机场 多 远|多|？",
                "How long have you studied Chinese?|你 学 汉语 多 长 时间 了|多|？",
                "How far is the company from home?|公司 离 家 多 远|多|？",
                "How old is younger sister?|妹妹 多 大|多|？",
                "How big is the classroom?|教室 多 大|多|？",
                "How long is this class?|这个 课 多 长|多|？",
                "How far is the supermarket?|超市 多 远|多|？",
                "How old is the child?|孩子 多 大|多|？",
                "How long did you wait?|你 等 多 长 时间|多|？",
                "How tall is dad?|爸爸 多 高|多|？",
                "How big is the class?|班 多 大|多|？",
                "How far is school?|学校 多 远|多|？",
                "How long is the exam?|考试 多 长 时间|多|？",
                "How old is the teacher?|老师 多 大|多|？",
                "How far is the station?|站 多 远|多|？",
                "How long have they worked?|他们 工作 多 长 时间 了|多|？",
                "How big is this room?|这个 房间 多 大|多|？",
            ]),
            gp("ji-approx", "几 for approximate numbers", "几 + measure; 十几; 几十",
               "几 can mean “several.” 十几 is 10–19; 几十 is several tens (20–99).",
               "我有几道题没有看懂。", "Wǒ yǒu jǐ dào tí méiyǒu kàndǒng.", "There were several questions I didn’t understand.", "g2",
               "几 = several; 十几 a bit over ten; 几十 dozens.", [
                "There are several people.|有 几 个 人|几|。",
                "I have several books.|我 有 几 本 书|几|。",
                "She drank several cups of coffee.|她 喝 了 几 杯 咖啡|几|。",
                "There are a dozen or so people.|有 十 几 个 人|几|。",
                "It costs a dozen or so kuai.|十 几 块 钱|几|。",
                "There are dozens of people.|有 几 十 个 人|几|。",
                "I have several questions.|我 有 几 道 题|几|。",
                "The class has a dozen or so students.|班 有 十 几 个 学生|几|。",
                "I waited several minutes.|我 等 了 几 分钟|几|。",
                "He bought dozens of books.|他 买 了 几 十 本 书|几|。",
                "There are several rooms.|有 几 个 房间|几|。",
                "Younger sister is a little over ten.|妹妹 十 几 岁|几|。",
                "I didn’t understand several questions.|几 道 题 我 没 看懂|几|。",
                "There are several male students.|有 几 个 男 学生|几|。",
                "There are a dozen or so girls.|有 十 几 个 女 学生|几|。",
                "Dad has several friends.|爸爸 有 几 个 朋友|几|。",
                "I waited several minutes.|我 等 了 几 分钟|几|。",
                "The school has dozens of teachers.|学校 有 几 十 个 老师|几|。",
                "I want several apples.|我 要 几 个 苹果|几|。",
                "She has a dozen or so cups.|她 有 十 几 个 杯子|几|。",
            ]),
            gp("duo-approx", "Number + 多", "number + 多 / measure + 多",
               "多 after a number means “a little more than.” Under 10, 多 follows the measure word: 三个多月. Over 10, 多 comes before the measure: 二十多个.",
               "三个多月了。", "Sān ge duō yuè le.", "It has been more than three months.", "g3",
               "Under 10: measure + 多. Over 10: number + 多 + measure.", [
                "It has been more than three months.|三 个 多 月 了|多|。",
                "More than two minutes.|两 个 多 分钟|多|。",
                "More than six kuai.|六 块 多|多|。",
                "More than nine years old.|九 岁 多|多|。",
                "More than ten people.|十 多 个 人|多|。",
                "More than twenty kuai.|二十 多 块|多|。",
                "More than thirty students.|三十 多 个 学生|多|。",
                "More than eighty books.|八十 多 本 书|多|。",
                "It is a little past seven.|七 点 多 了|多|。",
                "More than five months.|五 个 多 月|多|。",
                "More than four minutes.|四 个 多 分钟|多|。",
                "More than ten rooms.|十 多 个 房间|多|。",
                "More than twenty questions.|二十 多 道 题|多|。",
                "More than two weeks.|两 个 多 星期|多|。",
                "More than fifty people.|五十 多 个 人|多|。",
                "It has been more than one month.|一 个 多 月 了|多|。",
                "More than ten minutes.|十 多 分钟|多|。",
                "More than three years.|三 年 多|多|。",
                "More than thirty kuai.|三十 多 块 钱|多|。",
                "The class has more than twenty people.|班 有 二十 多 个 人|多|。",
            ]),
            gp("de-zui", "V 得 / 最", "verb + 得 + (最) + adjective",
               "得 after a verb introduces a state complement: how the action is done. 最 before an adjective or complement means “the most.”",
               "哥哥说汉语说得最好。", "Gēge shuō Hànyǔ shuō de zuì hǎo.", "Elder brother speaks Chinese the best.", "g4",
               "Verb + 得 + adjective. 最 = the most.", [
                "He speaks very well.|他 说 得 很 好|得|。",
                "Elder brother speaks the best.|哥哥 说 得 最 好|最|。",
                "She writes very well.|她 写 得 很 好|得|。",
                "Younger sister did not exam well.|妹妹 考 得 不 好|得|。",
                "I think he speaks the best.|我 觉得 他 说 得 最 好|最|。",
                "You walk very fast.|你 走 得 很 快|得|。",
                "She is the prettiest.|她 最 漂亮|最|。",
                "This room is the biggest.|这个 房间 最 大|最|。",
                "He studies very well.|他 学习 得 很 好|得|。",
                "I did the exam well.|我 考 得 很 好|得|。",
                "Dad speaks Chinese the best.|爸爸 说 汉语 说 得 最 好|最|。",
                "The child writes very fast.|孩子 写 得 很 快|得|。",
                "This class is the best.|这个 班 最 好|最|。",
                "She rests very little.|她 休息 得 很 少|得|。",
                "Mom cooks very well.|妈妈 做 得 很 好|得|。",
                "Who speaks the best?|谁 说 得 最 好|最|？",
                "He waits very long.|他 等 得 很 长|得|。",
                "This question is the hardest.|这 道 题 最 不 好|最|。",
                "I get up very early.|我 起床 得 很 早|得|。",
                "Younger sister is the smallest.|妹妹 最 小|最|。",
            ]),
        ],
    )
