from builder import L, gp, W, lesson_json


def lesson_11():
    return lesson_json(
        "11", 11, "中国新年", "Chinese New Year",
        [
            W("姐姐", "jiějie", "n.", "elder sister"),
            W("弟弟", "dìdi", "n.", "younger brother"),
            W("次", "cì", "m.w.", "times"),
            W("只有", "zhǐyǒu", "conj.", "only"),
            W("阴", "yīn", "adj.", "overcast"),
            W("晴", "qíng", "adj.", "sunny, clear"),
            W("眼睛", "yǎnjing", "n.", "eye"),
        ],
        L("Use the lesson word in a new sentence.", [
            "Elder sister is in China.|姐姐 在 中国|姐姐|。",
            "Younger brother came.|弟弟 来 了|弟弟|。",
            "I have been once.|我 来 过 一 次|次|。",
            "I only go home at New Year.|我 只有 新年 回 家|只有|。",
            "The sky is overcast.|天 阴 了|阴|。",
            "Today is sunny.|今天 很 晴|晴|。",
            "Dad’s eyes are not good.|爸爸 的 眼睛 不 太 好|眼睛|。",
            "Sister speaks Chinese well.|姐姐 汉语 说 得 很 好|姐姐|。",
            "Brother has been here once.|弟弟 来 过 一 次|次|。",
            "I go back only once a year.|我 一 年 只有 一 次 回 家|只有|。",
            "It may rain because it’s overcast.|天 阴 了 可能 下雨|阴|。",
            "We’ll go when it’s clear.|天 晴 了 再 去|晴|。",
            "I want a bigger phone for his eyes.|眼睛 不 好 要 大 的 手机|眼睛|。",
            "Younger brother worked in China.|弟弟 在 中国 工作 过|弟弟|。",
            "Elder sister will come at New Year.|姐姐 新年 会 来|姐姐|。",
            "I have seen her twice.|我 见 过 她 两 次|次|。",
            "Only she can help.|只有 她 可以 帮助|只有|。",
            "The weather is clear now.|现在 天 晴 了|晴|。",
            "My eyes are tired.|我 的 眼睛 不 好|眼睛|。",
            "It’s overcast today.|今天 阴|阴|。",
        ]),
        [
            gp("jiuyao", "就要…了", "就要 / 快要 / 快 / 要 + verb + 了",
               "就要…了 (also 快要…了, 快…了, 要…了) means something is about to happen.",
               "就要到中国的新年了。", "Jiù yào dào Zhōngguó de xīnnián le.", "Chinese New Year is about to arrive.", "g1",
               "就要 / 快要 / 要 + verb + 了 = about to.", [
                "Chinese New Year is about to arrive.|就要 到 新年 了|就要|。",
                "Dad is about to come back.|爸爸 就要 回来 了|就要|。",
                "It’s about to rain.|就要 下雨 了|就要|。",
                "The train is about to leave.|火车 快要 开 了|快要|。",
                "Chinese class is about to start.|汉语 课 要 开始 了|要|。",
                "I am about to go home.|我 就要 回 家 了|就要|。",
                "Younger brother is about to come.|弟弟 就要 来 了|就要|。",
                "Elder sister is about to leave.|姐姐 快要 走 了|快要|。",
                "The New Year is coming.|新年 快 到 了|快|。",
                "I’m about to finish.|我 就要 做完 了|就要|。",
                "She is about to leave hospital.|她 就要 出院 了|就要|。",
                "The plane is about to arrive.|飞机 就要 到 了|就要|。",
                "We are about to eat.|我们 要 吃 饭 了|要|。",
                "It’s about to rain.|天 就要 下雨 了|就要|。",
                "He is about to get up.|他 就要 起床 了|就要|。",
                "The exam is about to start.|考试 快要 开始 了|快要|。",
                "I am about to tell you.|我 就要 告诉 你 了|就要|。",
                "They are about to travel.|他们 就要 去 旅游 了|就要|。",
                "The weather is about to clear.|天 就要 晴 了|就要|。",
                "New Year is almost here.|就要 到 了|就要|。",
            ]),
            gp("ci-times", "Number + 次", "verb + number + 次 (+ object)",
               "次 counts times. Number + 次 often follows the verb. With a place it can go before or after the place; with a person it must follow the person.",
               "我弟弟来过一次。", "Wǒ dìdi láiguo yí cì.", "My younger brother has been here once.", "g2",
               "次 = times. Verb + number + 次.", [
                "Younger brother has been here once.|弟弟 来 过 一 次|次|。",
                "I have taken a plane three times.|我 坐 过 三 次 飞机|次|。",
                "They have seen the movie twice.|他们 看 过 两 次 电影|次|。",
                "I have been to Shanghai three times.|我 去 过 三 次 上海|次|。",
                "I have been here once.|我 来 过 一 次|次|。",
                "I have met you three times.|我 见 过 你 三 次|次|。",
                "We looked for him once.|我们 找 过 他 一 次|次|。",
                "The teacher called him twice.|老师 叫 了 他 两 次|次|。",
                "Elder sister has come twice.|姐姐 来 过 两 次|次|。",
                "I have asked once.|我 问 过 一 次|次|。",
                "He has been to Thailand once.|他 去 过 泰国 一 次|次|。",
                "I play basketball twice a week.|我 一 个 星期 打篮球 两 次|次|。",
                "She has taken the train three times.|她 坐 过 三 次 火车|次|。",
                "We have swum once.|我们 游泳 过 一 次|次|。",
                "Younger brother has seen me once.|弟弟 见 过 我 一 次|次|。",
                "I go home once a year.|我 一 年 回 家 一 次|次|。",
                "They have traveled twice.|他们 旅游 过 两 次|次|。",
                "I have used this phone once.|我 用 过 这 个 手机 一 次|次|。",
                "Dad has come three times.|爸爸 来 过 三 次|次|。",
                "I have taken photos twice.|我 照相 过 两 次|次|。",
            ]),
            gp("de-bi", "V 得 比", "A 比 B + V + 得 + adj  /  A + V + 得 + 比 + B + adj",
               "When a state complement and a comparison occur together: 他比我学得快 or 他学得比我快.",
               "她说得比我好。", "Tā shuō de bǐ wǒ hǎo.", "She speaks better than I do.", "g3",
               "Two orders: A 比 B V 得 adj, or A V 得 比 B adj.", [
                "She speaks better than I do.|她 说 得 比 我 好|比|。",
                "He learns faster than I do.|他 学 得 比 我 快|比|。",
                "Xiaoming runs faster than I do.|他 跑 得 比 我 快|比|。",
                "Elder sister speaks better than younger brother.|姐姐 说 得 比 弟弟 好|比|。",
                "I write better than he does.|我 写 得 比 他 好|比|。",
                "She sings better than I do.|她 唱歌 唱 得 比 我 好|比|。",
                "Dad walks faster than mom.|爸爸 走 得 比 妈妈 快|比|。",
                "Younger brother gets up earlier than I do.|弟弟 起床 起 得 比 我 早|比|。",
                "He does exams better than I do.|他 考 得 比 我 好|比|。",
                "I rest more than she does.|我 休息 得 比 她 多|比|。",
                "Elder sister works faster.|姐姐 做 得 比 我 快|比|。",
                "She swims better than I do.|她 游泳 游 得 比 我 好|比|。",
                "I wait longer than he does.|我 等 得 比 他 长|比|。",
                "Younger brother eats faster.|弟弟 吃 得 比 我 快|比|。",
                "He speaks Chinese better than I do.|他 说 汉语 说 得 比 我 好|比|。",
                "Mom cooks better than I do.|妈妈 做 得 比 我 好|比|。",
                "I jog faster than dad.|我 跑步 跑 得 比 爸爸 快|比|。",
                "She sees better than I do.|她 看 得 比 我 好|比|。",
                "Elder brother asks more than I do.|哥哥 问 得 比 我 多|比|。",
                "They play better than we do.|他们 玩儿 得 比 我们 好|比|。",
            ]),
        ],
    )


def lesson_12():
    return lesson_json(
        "12", 12, "复习", "Review",
        [
            W("度", "dù", "m.w.", "degree"),
            W("说话", "shuōhuà", "v.", "to speak, to talk"),
            W("祝", "zhù", "v.", "to wish"),
            W("长", "zhǎng", "v.", "to grow"),
            W("像", "xiàng", "v./adj.", "to look like"),
            W("舅舅", "jiùjiu", "n.", "uncle (mother’s brother)"),
            W("彩色", "cǎisè", "adj.", "colorful"),
            W("铅笔", "qiānbǐ", "n.", "pencil"),
            W("西瓜", "xīguā", "n.", "watermelon"),
            W("鸡蛋", "jīdàn", "n.", "egg"),
            W("骑", "qí", "v.", "to ride"),
            W("自行车", "zìxíngchē", "n.", "bicycle"),
            W("贵", "guì", "adj.", "expensive"),
            W("慢", "màn", "adj.", "slow"),
        ],
        L("Use the lesson word in a new sentence.", [
            "It is ten degrees.|十 度|度|。",
            "Who are you talking to?|你 在 和 谁 说话|说话|？",
            "I wish you a happy New Year.|祝 你 新年 快乐|祝|。",
            "They look alike.|他们 长得 很 像|像|。",
            "Uncle gave me a gift.|舅舅 给 我 礼物|舅舅|。",
            "The pencils are colorful.|铅笔 是 彩色 的|彩色|。",
            "I have a pencil.|我 有 铅笔|铅笔|。",
            "Watermelon is delicious.|西瓜 很 好吃|西瓜|。",
            "I bought eggs.|我 买 了 鸡蛋|鸡蛋|。",
            "He rides a bike.|他 骑 自行车|骑|。",
            "The bike is new.|自行车 很 新|自行车|。",
            "Beef is expensive.|这个 很 贵|贵|。",
            "The bike is slow.|自行车 很 慢|慢|。",
            "I like talking.|我 喜欢 说话|说话|。",
            "She looks like mom.|她 像 妈妈|像|。",
            "Uncle is swimming.|舅舅 在 游泳|舅舅|。",
            "The watermelon is expensive.|西瓜 很 贵|贵|。",
            "I ride slowly.|我 骑 得 很 慢|慢|。",
            "Wish him well.|祝 他 好|祝|。",
            "It is over ten degrees.|十 几 度|度|。",
        ]),
        [
            gp("approx-review", "Approximate numbers (review)", "几 / 十几 / 几十 / number + 多",
               "Review of 几 and 多 for approximate numbers, now with 度, 颜色, and other review words.",
               "每天都有十几度呢。", "Měi tiān dōu yǒu shíjǐ dù ne.", "It’s over ten degrees every day.", "g1",
               "几 and 多 still mark approximate numbers.", [
                "It’s over ten degrees every day.|每 天 都 有 十 几 度 呢|几|。",
                "There are more than twenty colors.|有 二十 多 个 颜色|多|。",
                "Several pencils.|几 支 铅笔|几|。",
                "Dozens of people.|几 十 个 人|几|。",
                "More than two weeks.|两 个 多 星期|多|。",
                "More than five months.|五 个 多 月|多|。",
                "More than ten degrees.|十 多 度|多|。",
                "Several watermelons.|几 个 西瓜|几|。",
                "More than thirty eggs.|三十 多 个 鸡蛋|多|。",
                "A dozen or so bikes.|十 几 个 自行车|几|。",
                "Several friends.|几 个 朋友|几|。",
                "More than eighty kuai.|八十 多 块|多|。",
                "It’s a little over ten degrees.|十 几 度|几|。",
                "More than three years.|三 年 多|多|。",
                "Several colorful pencils.|几 支 彩色 铅笔|几|。",
                "Dozens of tickets.|几 十 张 票|几|。",
                "More than four hours.|四 个 多 小时|多|。",
                "Several questions.|几 道 题|几|。",
                "More than twenty people.|二十 多 个 人|多|。",
                "A dozen or so rooms.|十 几 个 房间|几|。",
            ]),
            gp("state-review", "State complement (review)", "verb + 得 + adjective",
               "Review of 得 after a verb: 说得很好, 长得真像, 骑得很慢.",
               "她汉语说得很好。", "Tā Hànyǔ shuō de hěn hǎo.", "She speaks Chinese very well.", "g2",
               "Verb + 得 + how it is done.", [
                "She speaks Chinese very well.|她 汉语 说 得 很 好|得|。",
                "You speak really well.|你 说 得 真 好|得|。",
                "You two look really alike.|你们 长得 真 像|长得|。",
                "He runs very fast.|他 跑 得 很 快|得|。",
                "Mom cooks very well.|妈妈 做 得 很 好吃|得|。",
                "She sings very well.|她 唱 得 很 好听|得|。",
                "I ride very slowly.|我 骑 得 很 慢|得|。",
                "Uncle speaks very fast.|舅舅 说 得 很 快|得|。",
                "The child writes well.|孩子 写 得 很 好|得|。",
                "He eats slowly.|他 吃 得 很 慢|得|。",
                "I talk a lot.|我 说话 说 得 很 多|得|。",
                "She looks like dad.|她 长得 像 爸爸|长得|。",
                "You walk too slowly.|你 走 得 太 慢|得|。",
                "The bike goes slowly.|自行车 走 得 很 慢|得|。",
                "He does exams well.|他 考 得 很 好|得|。",
                "I get up early.|我 起床 得 很 早|得|。",
                "This tastes good.|这个 吃 得 很 好|得|。",
                "Younger brother runs slowly.|弟弟 跑 得 很 慢|得|。",
                "Elder sister speaks well.|姐姐 说 得 很 好|得|。",
                "I wait a long time.|我 等 得 很 长|得|。",
            ]),
            gp("redup-review", "Verb reduplication (review)", "AA / ABAB",
               "Monosyllabic verbs reduplicate as AA or A一A. Disyllabic verbs use ABAB: 运动运动, 准备准备.",
               "他想运动运动。", "Tā xiǎng yùndòng yùndòng.", "He wants to get some exercise.", "g3",
               "AA or ABAB makes the action short and casual.", [
                "He wants to get some exercise.|他 想 运动运动|运动运动|。",
                "Go get ready.|你 准备准备|准备准备|。",
                "Study a bit.|学习学习|学习学习|。",
                "Rest a bit.|休息休息|休息休息|。",
                "Take a look.|你 看看|看看|。",
                "Think about it.|你 想想|想想|。",
                "Walk a bit.|我们 走走|走走|。",
                "Ask around.|你 问问|问问|。",
                "Talk about it.|你 说说|说说|。",
                "Introduce him.|介绍介绍|介绍介绍|。",
                "Ride a bit.|骑 骑 自行车|骑|。",
                "Look at the pencils.|看看 铅笔|看看|。",
                "Have a taste of the melon.|看看 西瓜|看看|。",
                "Rest, then go.|休息休息 再 去|休息休息|。",
                "Get some exercise this morning.|早上 运动运动|运动运动|。",
                "Prepare the gift.|准备准备 礼物|准备准备|。",
                "Study Chinese a bit.|学习学习 汉语|学习学习|。",
                "Walk outside.|外面 走走|走走|。",
                "Ask uncle.|问问 舅舅|问问|。",
                "Have a look at the eggs.|看看 鸡蛋|看看|。",
            ]),
            gp("bi-yidian", "比 + complement", "A 比 B + adj + 一点儿 / 得多 / number",
               "After 比 you can add how much: 贵一点儿, 高得多, 贵三块钱.",
               "今天的西瓜比昨天的贵一点儿。", "Jīntiān de xīguā bǐ zuótiān de guì yìdiǎnr.", "Today’s watermelon is a bit more expensive than yesterday’s.", "g4",
               "比 + adj + 一点儿 / 得多 / a number.", [
                "Today’s watermelon is a bit more expensive.|西瓜 比 昨天 贵 一点儿|比|。",
                "Elder brother is a bit taller than sister.|哥哥 比 姐姐 高 一点儿|比|。",
                "Today is much colder than yesterday.|今天 比 昨天 冷 得 多|比|。",
                "This bike is a bit slower.|自行车 比 那个 慢 一点儿|比|。",
                "Eggs are three kuai more expensive.|鸡蛋 比 那个 贵 三 块|比|。",
                "Uncle is much taller.|舅舅 比 我 高 得 多|比|。",
                "This pencil is a bit more expensive.|铅笔 比 那个 贵 一点儿|比|。",
                "I am a bit slower.|我 比 你 慢 一点儿|比|。",
                "Watermelon is much more delicious.|西瓜 比 苹果 好吃 得 多|比|。",
                "The colorful one is a bit prettier.|彩色 的 比 黑 的 漂亮 一点儿|比|。",
                "Talking is a bit slower.|说话 比 写 慢 一点儿|比|。",
                "This is much more expensive.|这个 比 那个 贵 得 多|比|。",
                "She looks a bit more like mom.|她 比 我 像 妈妈 一点儿|比|。",
                "The bike is much slower than the train.|自行车 比 火车 慢 得 多|比|。",
                "Today is a bit more overcast.|今天 比 昨天 阴 一点儿|比|。",
                "He is a bit taller than younger brother.|他 比 弟弟 高 一点儿|比|。",
                "This room is much bigger.|这个 房间 比 那个 大 得 多|比|。",
                "I ride a bit slower.|我 骑 得 比 你 慢 一点儿|比|。",
                "Eggs are a bit more expensive than watermelon.|鸡蛋 比 西瓜 贵 一点儿|比|。",
                "New Year is much happier.|新年 比 昨天 快乐 得 多|比|。",
            ]),
        ],
    )
