from builder import L, gp, W, lesson_json


def lesson_07():
    return lesson_json(
        "07", 7, "谈论旅游", "Talking about travel",
        [
            W("快乐", "kuàilè", "adj.", "happy"),
            W("礼物", "lǐwù", "n.", "gift, present"),
            W("手表", "shǒubiǎo", "n.", "watch"),
            W("非常", "fēicháng", "adv.", "very"),
            W("玩儿", "wánr", "v.", "to play, to have fun"),
            W("还", "hái", "adv.", "passably; still"),
            W("去年", "qùnián", "n.", "last year"),
            W("雪", "xuě", "n.", "snow"),
            W("路", "lù", "n.", "road, way"),
            W("白", "bái", "adj.", "white"),
            W("好吃", "hǎochī", "adj.", "delicious"),
            W("宾馆", "bīnguǎn", "n.", "hotel"),
            W("游泳", "yóuyǒng", "v.", "to swim"),
        ],
        L("Use the lesson word in a new sentence.", [
            "Happy New Year.|新年 快乐|快乐|。",
            "This gift is for you.|这个 礼物 是 给 你 的|礼物|。",
            "The watch is new.|手表 很 新|手表|。",
            "I like it very much.|我 非常 喜欢|非常|。",
            "The children are playing.|孩子 在 玩儿|玩儿|。",
            "It’s not bad.|还 好|还|。",
            "I went last year.|我 去年 去 了|去年|。",
            "There is snow.|有 雪|雪|。",
            "The road is long.|路 很 长|路|。",
            "The snow is white.|雪 是 白 的|白|。",
            "This dish is delicious.|这个 菜 很 好吃|好吃|。",
            "The hotel is big.|宾馆 很 大|宾馆|。",
            "I like swimming.|我 喜欢 游泳|游泳|。",
            "The gift is a watch.|礼物 是 手表|手表|。",
            "Last year was cold.|去年 很 冷|去年|。",
            "The road is white.|路 是 白 的|路|。",
            "The hotel food is good.|宾馆 的 菜 很 好吃|好吃|。",
            "Let’s play.|我们 玩儿 吧|玩儿|。",
            "I am very happy.|我 非常 高兴|非常|。",
            "She swims every day.|她 每 天 游泳|游泳|。",
        ]),
        [
            gp("de-phrase", "的-phrase", "pronoun / adjective / verb + 的",
               "的 after a person, adjective, or verb can stand for a noun that is already clear: 我的 = mine, 红的 = the red one, 开车的 = the person who drives.",
               "这是我的。", "Zhè shì wǒ de.", "This is mine.", "g1",
               "的 can replace a noun you both know.", [
                "This is mine.|这 是 我 的|的|。",
                "That is dad’s.|那 是 爸爸 的|的|。",
                "This book is not mine.|这 本 书 不 是 我 的|的|。",
                "My cup is the red one.|我 的 杯子 是 红 的|的|。",
                "This gift is younger sister’s.|这个 礼物 是 妹妹 的|的|。",
                "The watch is his.|手表 是 他 的|的|。",
                "I want the cheap one.|我 要 便宜 的|的|。",
                "She likes the white one.|她 喜欢 白 的|的|。",
                "This hotel is theirs.|这个 宾馆 是 他们 的|的|。",
                "The delicious one is here.|好吃 的 在 这儿|的|。",
                "That is mom’s.|那 是 妈妈 的|的|。",
                "Is this yours?|这 是 你 的 吗|的|？",
                "I don’t want the small one.|我 不要 小 的|的|。",
                "The new one is pretty.|新 的 很 漂亮|的|。",
                "This is the teacher’s.|这 是 老师 的|的|。",
                "Elder brother’s is here.|哥哥 的 在 这儿|的|。",
                "I like the big one.|我 喜欢 大 的|的|。",
                "The red one is cheap.|红 的 很 便宜|的|。",
                "This ticket is mine.|这个 票 是 我 的|的|。",
                "Last year’s was better.|去年 的 很 好|的|。",
            ]),
            gp("shi-de", "是…的 (who did it)", "thing 是 person + verb + 的",
               "是 + person + verb + 的 emphasizes who did the action: 这本书是我买的.",
               "那是李明买的。", "Nà shì wǒ mǎi de.", "That is one I bought.", "g2",
               "是 + doer + verb + 的 names who did it.", [
                "This book is one I bought.|这 本 书 是 我 买 的|是|。",
                "Breakfast is one mom made.|饭 是 妈妈 做 的|的|。",
                "This character is one he wrote.|这个 字 是 他 写 的|的|。",
                "The gift is one dad bought.|礼物 是 爸爸 买 的|是|。",
                "The watch is one she found.|手表 是 她 找 的|的|。",
                "This ticket is one I bought.|这个 票 是 我 买 的|是|。",
                "The rice is one I cooked.|米饭 是 我 做 的|的|。",
                "This is not one I bought.|这 不 是 我 买 的|是|。",
                "The phone is one he bought.|手机 是 他 买 的|的|。",
                "The newspaper is one teacher bought.|报纸 是 老师 买 的|是|。",
                "This cup is one younger sister bought.|杯子 是 妹妹 买 的|的|。",
                "The hotel was one we found.|宾馆 是 我们 找 的|是|。",
                "This is one she wrote.|这 是 她 写 的|的|。",
                "The coffee is one I bought.|咖啡 是 我 买 的|是|。",
                "That is not one dad made.|那 不 是 爸爸 做 的|是|。",
                "This question is one I wrote.|这 道 题 是 我 写 的|的|。",
                "The milk is one mom bought.|牛奶 是 妈妈 买 的|是|。",
                "This is one they bought.|这 是 他们 买 的|的|。",
                "The clothes are ones she wears.|衣服 是 她 穿 的|是|。",
                "This train ticket is one I bought.|火车 票 是 我 买 的|的|。",
            ]),
            gp("hai-adj", "还 + adjective", "还 + 好 / 可以 / 行",
               "还 before an adjective often means “passably / not bad”: 还好, 还可以.",
               "还可以。", "Hái kěyǐ.", "Not bad.", "g3",
               "还 + adj = fairly / not too bad.", [
                "Not bad.|还 好|还|。",
                "It’s acceptable.|还 可以|还|。",
                "The hotel is all right.|宾馆 还 好|还|。",
                "The weather is not too bad.|天气 还 可以|还|。",
                "This watch is all right.|这个 手表 还 好|还|。",
                "The road is okay.|路 还 可以|还|。",
                "I’m still all right.|我 还 好|还|。",
                "The gift is acceptable.|礼物 还 可以|还|。",
                "Last year was all right.|去年 还 好|还|。",
                "Swimming is okay.|游泳 还 可以|还|。",
                "The food is not bad.|菜 还 好吃|还|。",
                "The room is all right.|房间 还 好|还|。",
                "Work is still okay.|工作 还 可以|还|。",
                "Her Chinese is all right.|她 的 汉语 还 好|还|。",
                "The ticket is acceptable.|票 还 可以|还|。",
                "Today is not too bad.|今天 还 好|还|。",
                "The class is okay.|课 还 可以|还|。",
                "This phone is all right.|这个 手机 还 好|还|。",
                "Thailand was okay.|泰国 还 可以|还|。",
                "The snow is pretty enough.|雪 还 漂亮|还|。",
            ]),
            gp("youdiar", "有点儿 + adjective", "有点儿 + adj",
               "有点儿 + adjective often shows a slight complaint: a bit too hot, a bit expensive, a bit far.",
               "天气有点儿热。", "Tiānqì yǒudiǎnr rè.", "The weather is a bit hot.", "g4",
               "有点儿 + adj = a bit (often not in a good way).", [
                "The weather is a bit hot.|天气 有点儿 热|有点儿|。",
                "This is a bit small.|这个 有点儿 小|有点儿|。",
                "That school is a bit far.|那个 学校 有点儿 远|有点儿|。",
                "I am a bit busy.|我 有点儿 忙|有点儿|。",
                "The room is a bit small.|房间 有点儿 小|有点儿|。",
                "The coffee is a bit hot.|咖啡 有点儿 热|有点儿|。",
                "The hotel is a bit far.|宾馆 有点儿 远|有点儿|。",
                "This watch is a bit big.|手表 有点儿 大|有点儿|。",
                "The road is a bit long.|路 有点儿 长|有点儿|。",
                "I am a bit cold.|我 有点儿 冷|有点儿|。",
                "The exam is a bit long.|考试 有点儿 长|有点儿|。",
                "She is a bit late.|她 有点儿 迟到|有点儿|。",
                "The dish is a bit hot.|菜 有点儿 热|有点儿|。",
                "This book is a bit small.|这 本 书 有点儿 小|有点儿|。",
                "Work is a bit much.|工作 有点儿 多|有点儿|。",
                "The child is a bit small.|孩子 有点儿 小|有点儿|。",
                "The station is a bit far.|站 有点儿 远|有点儿|。",
                "I am a bit tired of waiting.|我 等 得 有点儿 长|有点儿|。",
                "The time is a bit long.|时间 有点儿 长|有点儿|。",
                "Last year was a bit cold.|去年 有点儿 冷|有点儿|。",
            ]),
        ],
    )
