from builder import L, gp, W, lesson_json


def lesson_08():
    return lesson_json(
        "08", 8, "买东西", "Buying things",
        [
            W("一起", "yìqǐ", "adv.", "together"),
            W("生日", "shēngrì", "n.", "birthday"),
            W("件", "jiàn", "m.w.", "for clothes"),
            W("您", "nín", "pron.", "honorific you"),
            W("粉色", "fěnsè", "adj.", "pink"),
            W("别的", "biéde", "pron.", "other"),
            W("颜色", "yánsè", "n.", "color"),
            W("黑", "hēi", "adj.", "black"),
            W("拿", "ná", "v.", "to take, to hold"),
            W("就", "jiù", "adv.", "then / that’s settled"),
            W("服务员", "fúwùyuán", "n.", "waiter / salesperson"),
            W("比", "bǐ", "prep.", "than"),
            W("羊肉", "yángròu", "n.", "lamb, mutton"),
            W("鱼", "yú", "n.", "fish"),
            W("洗手间", "xǐshǒujiān", "n.", "bathroom"),
            W("洗", "xǐ", "v.", "to wash"),
            W("手", "shǒu", "n.", "hand"),
            W("门", "mén", "n.", "door"),
            W("外", "wài", "n.", "outside"),
        ],
        L("Use the lesson word in a new sentence.", [
            "Let’s go together.|我们 一起 去|一起|。",
            "Today is my birthday.|今天 是 我 的 生日|生日|。",
            "I want one piece of clothing.|我 要 一 件 衣服|件|。",
            "How are you? (polite)|您 好|您|。",
            "I like pink.|我 喜欢 粉色|粉色|。",
            "Do you have other colors?|有 别的 颜色 吗|别的|？",
            "What color is this?|这 是 什么 颜色|颜色|？",
            "This is black.|这 是 黑 的|黑|。",
            "Please take it.|请 拿|拿|。",
            "Then I’ll take this.|就 要 这个|就|。",
            "The waiter is here.|服务员 在|服务员|。",
            "This is better than that.|这个 比 那个 好|比|。",
            "I don’t eat lamb.|我 不 吃 羊肉|羊肉|。",
            "The fish is delicious.|鱼 很 好吃|鱼|。",
            "Where is the bathroom?|洗手间 在 哪儿|洗手间|？",
            "Wash your hands.|洗 手|洗|。",
            "My hands are cold.|手 很 冷|手|。",
            "The door is open.|门 开 了|门|。",
            "Wait outside.|在 外 等|外|。",
            "Let’s eat fish together.|我们 一起 吃 鱼|一起|。",
        ]),
        [
            gp("haoma", "…好吗", "statement + 好吗？",
               "好吗 after a suggestion asks “is that OK?” / “shall we?”",
               "我们一起去，好吗？", "Wǒmen yìqǐ qù, hǎo ma?", "Shall we go together?", "g1",
               "Put 好吗 after a plan to check it is OK.", [
                "Shall we go together?|我们 一起 去 好 吗|吗|？",
                "Will you call me tomorrow?|你 明天 给 我 打 电话 好 吗|吗|？",
                "Shall we watch a movie?|我们 看 电影 好 吗|吗|？",
                "Let’s eat fish, okay?|我们 吃 鱼 好 吗|吗|？",
                "Wait here, okay?|你 在 这儿 等 好 吗|吗|？",
                "Shall we go shopping?|我们 去 买 东西 好 吗|吗|？",
                "Help me, okay?|你 帮助 我 好 吗|吗|？",
                "Let’s rest, okay?|我们 休息 好 吗|吗|？",
                "Come in, okay?|你 进 来 好 吗|吗|？",
                "Shall we take the train?|我们 坐 火车 好 吗|吗|？",
                "Buy this, okay?|买 这个 好 吗|吗|？",
                "Let’s swim, okay?|我们 游泳 好 吗|吗|？",
                "Tell her, okay?|你 告诉 她 好 吗|吗|？",
                "Shall we eat lamb?|我们 吃 羊肉 好 吗|吗|？",
                "Wait outside, okay?|你 在 门 外 等 好 吗|吗|？",
                "Let’s go in the evening, okay?|我们 晚上 去 好 吗|吗|？",
                "Wash your hands, okay?|你 洗 手 好 吗|吗|？",
                "Shall we look together?|我们 一起 看 好 吗|吗|？",
                "Take the pink one, okay?|拿 粉色 的 好 吗|吗|？",
                "Let’s start, okay?|我们 开始 好 吗|吗|？",
            ]),
            gp("mw-redup", "Measure-word reduplication", "件件 / 个个 / 天天 + 都",
               "A doubled measure word means “every.” It is usually followed by 都, same idea as 每 + measure word.",
               "衣服件件都好看。", "Yīfu jiànjiàn dōu hǎokàn.", "Every piece of clothing looks good.", "g2",
               "Doubled measure word + 都 = every.", [
                "Every piece of clothing looks good.|衣服 件件 都 好看|件件|。",
                "Every student is happy.|学生 个个 都 很 高兴|个个|。",
                "He is late every day.|他 天天 都 迟到|天天|。",
                "Every room is pretty.|房间 个个 都 很 漂亮|个个|。",
                "Every piece is cheap.|件件 都 很 便宜|件件|。",
                "I walk every day.|我 天天 都 走|天天|。",
                "Every friend came.|朋友 个个 都 来 了|个个|。",
                "Every dish is delicious.|菜 个个 都 很 好吃|个个|。",
                "She works every day.|她 天天 都 上班|天天|。",
                "Every book is new.|书 本本 都 很 新|本本|。",
                "Every color is pretty.|颜色 个个 都 很 漂亮|个个|。",
                "Every waiter is nice.|服务员 个个 都 很 好|个个|。",
                "I swim every day.|我 天天 都 游泳|天天|。",
                "Every gift is good.|礼物 个个 都 很 好|个个|。",
                "Every piece of clothing is pink.|衣服 件件 都 是 粉色 的|件件|。",
                "They rest every day.|他们 天天 都 休息|天天|。",
                "Every child is here.|孩子 个个 都 在|个个|。",
                "Every ticket is cheap.|票 个个 都 很 便宜|个个|。",
                "I get up every day.|我 天天 都 起床|天天|。",
                "Every watch is black.|手表 个个 都 是 黑 的|个个|。",
            ]),
            gp("vp-de-n", "Verb phrase + 的 + noun", "VP 的 noun",
               "A verb phrase plus 的 describes a noun: 妈妈做的饭, 女孩子穿的衣服.",
               "我想买一件新的衣服。", "Wǒ xiǎng mǎi yí jiàn xīn de yīfu.", "I want to buy a new piece of clothing.", "g3",
               "Put 的 between the description and the noun.", [
                "Clothes that girls wear.|女 孩子 穿 的 衣服|的|。",
                "The car I just bought.|我 买 的 车|的|。",
                "Food mom made.|妈妈 做 的 饭|的|。",
                "The person who came with you.|和 你 一起 来 的 人|的|。",
                "The book I like.|我 喜欢 的 书|的|。",
                "The phone dad bought.|爸爸 买 的 手机|的|。",
                "The hotel we found.|我们 找 的 宾馆|的|。",
                "The ticket she bought.|她 买 的 票|的|。",
                "The fish this shop has.|这个 商店 的 鱼|的|。",
                "The pink clothes.|粉色 的 衣服|的|。",
                "The black one.|黑 的|的|。",
                "Friends who travel.|去 旅游 的 朋友|的|。",
                "The bathroom outside.|门 外 的 洗手间|的|。",
                "The waiter I know.|我 认识 的 服务员|的|。",
                "Clothes younger sister wears.|妹妹 穿 的 衣服|的|。",
                "The gift I bought.|我 买 的 礼物|的|。",
                "The train we take.|我们 坐 的 火车|的|。",
                "The color I like.|我 喜欢 的 颜色|的|。",
                "Work I do.|我 做 的 工作|的|。",
                "The birthday she likes.|她 喜欢 的 生日|的|。",
            ]),
            gp("bi-compare", "A 比 B + adjective", "A 比 B + adj",
               "比 compares two things: A 比 B + adjective. The negative is A 没有 B + adjective, not 不比 in this lesson.",
               "粉色的比黑色的好看。", "Fěnsè de bǐ hēisè de hǎokàn.", "The pink one looks better than the black one.", "g4",
               "A 比 B + adj. Negative: A 没有 B + adj.", [
                "The pink one looks better than the black one.|粉色 的 比 黑 的 好看|比|。",
                "Elder brother is older than I am.|哥哥 比 我 大|比|。",
                "Today is hotter than yesterday.|今天 比 昨天 热|比|。",
                "I am older than you.|我 比 你 大|比|。",
                "This phone is cheaper than that one.|这个 手机 比 那个 便宜|比|。",
                "Fish is more delicious than lamb.|鱼 比 羊肉 好吃|比|。",
                "This room is bigger than that room.|这个 房间 比 那个 房间 大|比|。",
                "She is not as old as he is.|她 没有 他 大|没有|。",
                "This is not as pretty as that.|这个 没有 那个 漂亮|没有|。",
                "The train is faster than walking.|火车 比 走 快|比|。",
                "My watch is newer than yours.|我 的 手表 比 你 的 新|比|。",
                "Beijing is farther than here.|北京 比 这儿 远|比|。",
                "Coffee is hotter than milk.|咖啡 比 牛奶 热|比|。",
                "This class is better than that class.|这个 班 比 那个 班 好|比|。",
                "Younger sister is smaller than I am.|妹妹 比 我 小|比|。",
                "This gift is prettier.|这个 礼物 比 那个 漂亮|比|。",
                "The hotel is cheaper than that one.|这个 宾馆 比 那个 便宜|比|。",
                "He speaks better than I do.|他 说 得 比 我 好|比|。",
                "Pink is prettier than black.|粉色 比 黑 好看|比|。",
                "This door is bigger than that door.|这个 门 比 那个 门 大|比|。",
            ]),
        ],
    )
