from builder import L, gp, W, lesson_json


def lesson_09():
    return lesson_json(
        "09", 9, "生病", "Getting ill",
        [
            W("生病", "shēngbìng", "v.", "to fall ill"),
            W("一直", "yìzhí", "adv.", "always, all along"),
            W("事情", "shìqing", "n.", "thing, matter"),
            W("忙", "máng", "adj.", "busy"),
            W("因为", "yīnwèi", "conj.", "because"),
            W("所以", "suǒyǐ", "conj.", "so, therefore"),
            W("出院", "chūyuàn", "v.", "to leave hospital"),
            W("完", "wán", "v.", "to finish"),
            W("按时", "ànshí", "adv.", "on time"),
            W("药", "yào", "n.", "medicine"),
            W("水果", "shuǐguǒ", "n.", "fruit"),
            W("运动", "yùndòng", "v./n.", "sport, to exercise"),
            W("错", "cuò", "adj.", "wrong"),
            W("跑步", "pǎobù", "v.", "to jog"),
            W("经常", "jīngcháng", "adv.", "often"),
            W("打篮球", "dǎlánqiú", "v.", "to play basketball"),
            W("踢足球", "tīzúqiú", "v.", "to play football"),
            W("更", "gèng", "adv.", "even more"),
        ],
        L("Use the lesson word in a new sentence.", [
            "He is ill.|他 生病 了|生病|。",
            "I have always liked this.|我 一直 喜欢|一直|。",
            "There are many things.|事情 很 多|事情|。",
            "I am busy today.|我 今天 很 忙|忙|。",
            "Because I am ill.|因为 我 生病 了|因为|。",
            "So I rest.|所以 我 休息|所以|。",
            "He can leave the hospital.|他 可以 出院 了|出院|。",
            "I finished the work.|我 做 完 了|完|。",
            "Take medicine on time.|按时 吃 药|按时|。",
            "This medicine is new.|这个 药 很 新|药|。",
            "I like fruit.|我 喜欢 水果|水果|。",
            "Exercise is good.|运动 很 好|运动|。",
            "That’s wrong.|那 是 错 的|错|。",
            "I jog in the morning.|我 早上 跑步|跑步|。",
            "I often swim.|我 经常 游泳|经常|。",
            "They play basketball.|他们 打篮球|打篮球|。",
            "I play football.|我 踢足球|踢足球|。",
            "I like this even more.|我 更 喜欢 这个|更|。",
            "Take the medicine.|吃 药|药|。",
            "Finish it.|做 完 了|完|。",
        ]),
        [
            gp("zenme-why", "怎么 (why)", "subject + 怎么 + situation",
               "怎么 can ask why, often with surprise: 你怎么没来？",
               "他怎么没来公司？", "Tā zěnme méi lái gōngsī?", "Why didn’t he come to the company?", "g1",
               "怎么 here means why (often surprised).", [
                "Why didn’t he come to the company?|他 怎么 没 来 公司|怎么|？",
                "Why are you so happy?|你 怎么 这么 高兴|怎么|？",
                "Why isn’t he eating?|他 怎么 不 吃 饭|怎么|？",
                "Why is it so hot outside?|外面 怎么 这么 热|怎么|？",
                "Why haven’t you slept?|你 怎么 还 没 睡觉|怎么|？",
                "Why is she ill?|她 怎么 生病 了|怎么|？",
                "Why didn’t you call?|你 怎么 没 打 电话|怎么|？",
                "Why are you standing outside?|你 怎么 在 外面|怎么|？",
                "Why is work so busy?|工作 怎么 这么 忙|怎么|？",
                "Why didn’t they come to class?|他们 怎么 没 来 上课|怎么|？",
                "Why is the child not playing?|孩子 怎么 不 玩儿|怎么|？",
                "Why are you still here?|你 怎么 还 在|怎么|？",
                "Why didn’t he take the medicine?|他 怎么 没 吃 药|怎么|？",
                "Why is younger sister late?|妹妹 怎么 迟到 了|怎么|？",
                "Why don’t you rest?|你 怎么 不 休息|怎么|？",
                "Why is this wrong?|这个 怎么 是 错 的|怎么|？",
                "Why do you jog every day?|你 怎么 每 天 跑步|怎么|？",
                "Why didn’t you wait?|你 怎么 没 等|怎么|？",
                "Why is he leaving the hospital?|他 怎么 出院 了|怎么|？",
                "Why are things so many?|事情 怎么 这么 多|怎么|？",
            ]),
            gp("yinwei-suoyi", "因为…所以", "因为 cause，所以 result",
               "因为 introduces the cause and 所以 the result. You can use both, or only one of them.",
               "因为没有休息好，所以生病了。", "Yīnwèi méiyǒu xiūxi hǎo, suǒyǐ shēngbìng le.", "Because he didn’t rest well, he got ill.", "g2",
               "因为 = because; 所以 = so.", [
                "Because he is ill, he didn’t go.|因为 他 生病 了 所以 他 没 去|因为|。",
                "He runs every day, so he is healthy.|他 每 天 跑步 所以 身体 很 好|所以|。",
                "Because it is raining, we didn’t play football.|因为 下雨 了 所以 我们 没 踢足球|因为|。",
                "I am busy, so I didn’t rest.|我 很 忙 所以 没 休息|所以|。",
                "Because I finished, I can go.|因为 我 做完 了 所以 我 可以 去|因为|。",
                "She takes medicine on time, so she is better.|她 按时 吃 药 所以 好 了|所以|。",
                "Because work is a lot, he is ill.|因为 事情 很 多 所以 他 生病 了|因为|。",
                "I like fruit, so I eat apples.|我 喜欢 水果 所以 我 吃 苹果|所以|。",
                "Because I am wrong, I will say it again.|因为 我 错 了 所以 我 再 说|因为|。",
                "He exercises, so he is not ill.|他 运动 所以 不 生病|所以|。",
                "Because she is still working, she cannot leave.|因为 她 还 没 做完 所以 不 出院|因为|。",
                "I often jog, so I am healthy.|我 经常 跑步 所以 身体 好|所以|。",
                "Because it is cold, I don’t swim.|因为 很 冷 所以 我 不 游泳|因为|。",
                "Dad is busy, so he didn’t come.|爸爸 很 忙 所以 没 来|所以|。",
                "Because I like basketball, I play.|因为 我 喜欢 打篮球 所以 我 打篮球|因为|。",
                "The medicine is good, so I take it.|药 很 好 所以 我 吃|所以|。",
                "Because I have no time, I don’t exercise.|因为 我 没有 时间 所以 不 运动|因为|。",
                "He is better, so he can leave hospital.|他 好 了 所以 可以 出院|所以|。",
                "Because younger sister is ill, she rests.|因为 妹妹 生病 了 所以 她 休息|因为|。",
                "I finished, so I am happy.|我 做完 了 所以 很 高兴|所以|。",
            ]),
            gp("hai-mei", "还 / 还没", "还在 + verb / 还没 + verb",
               "还 means still. 还在 + verb = still doing it. 还没 + verb = still haven’t done it.",
               "你怎么还没睡觉？", "Nǐ zěnme hái méi shuìjiào?", "Why haven’t you gone to bed yet?", "g3",
               "还在 = still doing; 还没 = still not.", [
                "Why haven’t you gone to bed yet?|你 怎么 还 没 睡觉|还|？",
                "He is still sleeping.|他 还 在 睡觉|还|。",
                "She is still eating.|她 还 在 吃 饭|还|。",
                "They are still taking the exam.|他们 还 在 考试|还|。",
                "I still haven’t finished.|我 还 没 做完|还|。",
                "He still hasn’t come.|他 还 没 来|还|。",
                "Younger sister still hasn’t eaten.|妹妹 还 没 吃|还|。",
                "I am still waiting.|我 还 在 等|还|。",
                "Dad is still at the company.|爸爸 还 在 公司|还|。",
                "She still hasn’t left the hospital.|她 还 没 出院|还|。",
                "He is still ill.|他 还 在 生病|还|。",
                "I still haven’t taken the medicine.|我 还 没 吃 药|还|。",
                "They are still playing football.|他们 还 在 踢足球|还|。",
                "Mom is still working.|妈妈 还 在 工作|还|。",
                "I still haven’t rested.|我 还 没 休息|还|。",
                "The child is still playing.|孩子 还 在 玩儿|还|。",
                "He still hasn’t gotten up.|他 还 没 起床|还|。",
                "We are still exercising.|我们 还 在 运动|还|。",
                "She still hasn’t told me.|她 还 没 告诉 我|还|。",
                "I am still jogging.|我 还 在 跑步|还|。",
            ]),
            gp("ne-mood", "…呢 (emphasis)", "statement + 呢",
               "呢 at the end of a statement can add emphasis, as if you are reminding the listener: it really is that way.",
               "最少还要一个星期呢！", "Zuì shǎo hái yào yí ge xīngqī ne!", "It will take at least another week!", "g4",
               "呢 here adds a convincing or emphatic tone.", [
                "It takes two hours from home.|从 家 到 公司 要 两 个 小时 呢|呢|。",
                "He has seven children.|他 有 七 个 孩子 呢|呢|。",
                "It’s still early.|现在 还 早 呢|呢|。",
                "Walking to the supermarket takes an hour.|走 去 超市 要 一 个 小时 呢|呢|。",
                "I still have work.|我 还 有 工作 呢|呢|。",
                "She has been ill for a week.|她 生病 一 个 星期 了 呢|呢|。",
                "There are still many things.|事情 还 很 多 呢|呢|。",
                "Dad is still busy.|爸爸 还 很 忙 呢|呢|。",
                "I haven’t finished yet.|我 还 没 做完 呢|呢|。",
                "The hospital is far.|医院 很 远 呢|呢|。",
                "He needs to rest more.|他 还 要 休息 呢|呢|。",
                "This medicine is really good.|这个 药 很 好 呢|呢|。",
                "I jog every morning.|我 每 天 早上 跑步 呢|呢|。",
                "Younger sister still hasn’t eaten.|妹妹 还 没 吃 呢|呢|。",
                "We waited a long time.|我们 等 了 很 长 时间 呢|呢|。",
                "He can leave tomorrow.|他 明天 可以 出院 呢|呢|。",
                "There is still a lot of fruit.|水果 还 很 多 呢|呢|。",
                "I like basketball even more.|我 更 喜欢 打篮球 呢|呢|。",
                "Class is still going.|课 还 没 完 呢|呢|。",
                "She always takes medicine on time.|她 一直 按时 吃 药 呢|呢|。",
            ]),
        ],
    )
