from builder import L, gp, W, lesson_json


def lesson_04():
    return lesson_json(
        "04", 4, "找汉语学校", "Find a Chinese school",
        [
            W("正在", "zhèngzài", "adv.", "in the process of"),
            W("虽然", "suīrán", "conj.", "although"),
            W("但是", "dànshì", "conj.", "but, yet"),
            W("晚上", "wǎnshang", "n.", "evening, night"),
            W("开始", "kāishǐ", "v.", "to begin, to start"),
            W("课", "kè", "n.", "class, lesson"),
            W("让", "ràng", "v.", "to ask, to let, to allow"),
            W("帮助", "bāngzhù", "v.", "to help"),
            W("懂", "dǒng", "v.", "to understand"),
            W("长", "cháng", "adj.", "long"),
            W("时间", "shíjiān", "n.", "time"),
            W("休息", "xiūxi", "v.", "to rest"),
            W("吧", "ba", "part.", "suggestion particle"),
        ],
        L("Use the lesson word in a new sentence.", [
            "I am looking for a school.|我 正在 找 学校|正在|。",
            "Although it is hot, I will go.|虽然 很 热 但是 我 去|虽然|。",
            "I like it, but he does not.|我 喜欢 但是 他 不 喜欢|但是|。",
            "We start in the evening.|我们 晚上 开始|晚上|。",
            "The class starts tomorrow.|课 明天 开始|课|。",
            "Let her rest.|让 她 休息|让|。",
            "This book can help you.|这 本 书 帮助 你|帮助|。",
            "I understand now.|我 懂 了|懂|。",
            "The time is long.|时间 很 长|长|。",
            "I don’t have time.|我 没有 时间|时间|。",
            "Let’s rest.|我们 休息 吧|休息|。",
            "Let’s go.|我们 去 吧|吧|。",
            "She is watching TV.|她 正在 看 电视|正在|。",
            "Class starts at seven.|课 七 点 开始|开始|。",
            "Dad lets me come in.|爸爸 让 我 进|让|。",
            "I understood the Chinese.|我 听懂 汉语 了|听懂|。",
            "The evening is very hot.|晚上 很 热|晚上|。",
            "Although I am busy, I will go.|虽然 我 很 忙 但是 我 去|虽然|。",
            "Rest a bit.|休息 一下|休息|。",
            "Let’s wait.|我们 等 吧|吧|。",
        ]),
        [
            gp("bushima", "不是…吗", "不是…吗？",
               "不是…吗 is a rhetorical question. You already know the answer; you are reminding someone or showing surprise.",
               "你不是老师吗？", "Nǐ búshì lǎoshī ma?", "You are a teacher, aren’t you?", "g1",
               "不是…吗 asks a question you think you already know.", [
                "You are a teacher, aren’t you?|你 不是 老师 吗|不是|？",
                "He can speak Chinese, can’t he?|他 不是 会 说 汉语 吗|不是|？",
                "She is at the company, isn’t she?|她 不是 在 公司 吗|不是|？",
                "This is your book, isn’t it?|这 不是 你 的 书 吗|不是|？",
                "You are going today, aren’t you?|你 今天 不是 去 吗|不是|？",
                "He already left, didn’t he?|他 不是 走 了 吗|不是|？",
                "We have a class, don’t we?|我们 不是 有 课 吗|不是|？",
                "Dad is at home, isn’t he?|爸爸 不是 在 家 吗|不是|？",
                "This apartment is close, isn’t it?|这个 房子 不是 很 近 吗|不是|？",
                "You like coffee, don’t you?|你 不是 喜欢 咖啡 吗|不是|？",
                "She is a student, isn’t she?|她 不是 学生 吗|不是|？",
                "The child already arrived, didn’t he?|孩子 不是 到 了 吗|不是|？",
                "You are not going to work, are you?|你 不是 不 上班 吗|不是|？",
                "This is a new school, isn’t it?|这 不是 新 学校 吗|不是|？",
                "He is waiting, isn’t he?|他 不是 在 等 吗|不是|？",
                "We start this evening, don’t we?|我们 不是 晚上 开始 吗|不是|？",
                "Mom can help, can’t she?|妈妈 不是 会 帮助 吗|不是|？",
                "You understood, didn’t you?|你 不是 懂 了 吗|不是|？",
                "The shop is beside the station, isn’t it?|商店 不是 在 站 旁边 吗|不是|？",
                "They are resting, aren’t they?|他们 不是 在 休息 吗|不是|？",
            ]),
            gp("suiran-danshi", "虽然…但是", "虽然 clause 1，但是 clause 2",
               "虽然 means although and 但是 means but. Chinese uses them together in one sentence.",
               "虽然很热，但是我去。", "Suīrán hěn rè, dànshì wǒ qù.", "Although it is hot, I will go.", "g2",
               "虽然 and 但是 work as a pair.", [
                "Although it is hot, I will go.|虽然 很 热 但是 我 去|虽然|。",
                "Although I am busy, I like this.|虽然 我 很 忙 但是 我 喜欢|但是|。",
                "Although the apartment is far, it is pretty.|虽然 房子 很 远 但是 很 漂亮|虽然|。",
                "Although he can speak Chinese, the child cannot.|虽然 他 会 说 汉语 但是 孩子 不 会|但是|。",
                "Although it is cold, we will go out.|虽然 很 冷 但是 我们 出 去|虽然|。",
                "Although I like coffee, I drink tea.|虽然 我 喜欢 咖啡 但是 我 喝 茶|但是|。",
                "Although work is a lot, I am not late.|虽然 工作 很 多 但是 我 不 迟到|虽然|。",
                "Although the school is new, it is small.|虽然 学校 很 新 但是 很 小|但是|。",
                "Although I don’t have time, I will wait.|虽然 我 没有 时间 但是 我 等|虽然|。",
                "Although she is tired, she still works.|虽然 她 很 忙 但是 她 上班|但是|。",
                "Although milk is good, I don’t like it.|虽然 牛奶 很 好 但是 我 不 喜欢|虽然|。",
                "Although home is far, I am not late.|虽然 家 很 远 但是 我 不 迟到|但是|。",
                "Although the class is long, I like it.|虽然 课 很 长 但是 我 喜欢|虽然|。",
                "Although he is a student, he works.|虽然 他 是 学生 但是 他 工作|但是|。",
                "Although the room is small, it is pretty.|虽然 房间 很 小 但是 很 漂亮|虽然|。",
                "Although I understood, I will ask.|虽然 我 懂 了 但是 我 问|但是|。",
                "Although it is evening, we still go.|虽然 是 晚上 但是 我们 去|虽然|。",
                "Although dad lets me go, I don’t want to.|虽然 爸爸 让 我 去 但是 我 不想 去|但是|。",
                "Although the supermarket is close, I walk slowly.|虽然 超市 很 近 但是 我 走|虽然|。",
                "Although they rest, they still help.|虽然 他们 休息 但是 他们 帮助 我|但是|。",
            ]),
            gp("result-comp", "Result complement", "verb + 懂 / 见 / 到 / 好",
               "A result complement after a verb shows the outcome: 听懂 understood by listening, 看见 saw, 找到 found, 做好 finished well. Negate with 没, and do not use 了.",
               "我听懂了。", "Wǒ tīngdǒng le.", "I understood (by listening).", "g3",
               "The second verb or adjective is the result of the first.", [
                "I understood (by listening).|我 听懂 了|听懂|。",
                "I saw the cat.|我 看见 猫 了|看见|。",
                "She found a school.|她 找到 学校 了|找到|。",
                "Mom finished cooking.|妈妈 做好 饭 了|做好|。",
                "He understood the Chinese.|他 听懂 汉语 了|听懂|。",
                "I did not see him.|我 没 看见 他|看见|。",
                "They did not find the company.|他们 没 找到 公司|找到|。",
                "I did not understand.|我 没 听懂|听懂|。",
                "Did you see the child?|你 看见 孩子 了 吗|看见|？",
                "Did she find the book?|她 找到 书 了 吗|找到|？",
                "I understood this lesson.|我 听懂 课 了|听懂|。",
                "He saw the teacher.|他 看见 老师 了|看见|。",
                "We found the apartment.|我们 找到 房子 了|找到|。",
                "Dad finished the work.|爸爸 做好 工作 了|做好|。",
                "I cannot understand yet.|我 没 听懂|听懂|。",
                "She did not see mom.|她 没 看见 妈妈|看见|。",
                "I found a new school.|我 找到 新 学校 了|找到|。",
                "You understood, didn’t you?|你 听懂 了 吗|听懂|？",
                "He did not finish cooking.|他 没 做好 饭|做好|。",
                "I saw everyone.|我 看见 大家 了|看见|。",
            ]),
            gp("rang", "让 + someone + verb", "subject + 让 + person + verb",
               "让 introduces a pivotal sentence: you let or ask someone to do something. 请 and 叫 work the same way.",
               "你让他们休息一下吧。", "Nǐ ràng tāmen xiūxi yíxià ba.", "Ask them to rest a bit.", "g4",
               "让 + person + verb.", [
                "Ask them to rest.|你 让 他们 休息|让|。",
                "Mom lets me go.|妈妈 让 我 去|让|。",
                "Let her come in.|让 她 进|让|。",
                "Dad asks me to wait.|爸爸 让 我 等|让|。",
                "The teacher lets us rest.|老师 让 我们 休息|让|。",
                "Let him look.|让 他 看|让|。",
                "She lets the child drink milk.|她 让 孩子 喝 牛奶|让|。",
                "Let me help you.|让 我 帮助 你|让|。",
                "They let us start.|他们 让 我们 开始|让|。",
                "Don’t let him be late.|别 让 他 迟到|让|。",
                "Let everyone come in.|让 大家 进|让|。",
                "I let my friend look.|我 让 朋友 看|让|。",
                "Let the student write.|让 学生 写|让|。",
                "Mom lets us watch TV.|妈妈 让 我们 看 电视|让|。",
                "Let her find a school.|让 她 找 学校|让|。",
                "The company lets him rest.|公司 让 他 休息|让|。",
                "Let me say it.|让 我 说|让|。",
                "He lets me drink tea.|他 让 我 喝 茶|让|。",
                "Let the child sleep.|让 孩子 睡觉|让|。",
                "Please let her wait.|请 让 她 等|让|。",
            ]),
            gp("ba-suggest", "…吧", "statement + 吧",
               "吧 at the end of a sentence turns it into a suggestion: let’s… / how about…",
               "我们去吧。", "Wǒmen qù ba.", "Let’s go.", "g5",
               "吧 at the end makes a suggestion.", [
                "Let’s go.|我们 去 吧|吧|。",
                "Let’s rest.|我们 休息 吧|吧|。",
                "Have some tea.|你 喝 茶 吧|吧|。",
                "Let’s wait.|我们 等 吧|吧|。",
                "Ask the teacher.|你 问 老师 吧|吧|。",
                "Let’s start.|我们 开始 吧|吧|。",
                "Come in.|你 进 吧|吧|。",
                "Let’s look at the apartment.|我们 看 房子 吧|吧|。",
                "Drink some milk.|你 喝 牛奶 吧|吧|。",
                "Let’s go to class.|我们 去 上课 吧|吧|。",
                "You rest.|你 休息 吧|吧|。",
                "Let’s eat.|我们 吃 吧|吧|。",
                "Call dad.|你 打 电话 吧|吧|。",
                "Let’s walk.|我们 走 吧|吧|。",
                "Have a look.|你 看看 吧|吧|。",
                "Let’s wait for her.|我们 等 她 吧|吧|。",
                "Go home.|你 回 家 吧|吧|。",
                "Let’s help him.|我们 帮助 他 吧|吧|。",
                "Sit down.|你 坐 吧|吧|。",
                "Let’s drink coffee.|我们 喝 咖啡 吧|吧|。",
            ]),
        ],
    )
